// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: search/search.proto

package search

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Tag with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Tag) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Tag with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in TagMultiError, or nil if none found.
func (m *Tag) ValidateAll() error {
	return m.validate(true)
}

func (m *Tag) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	// no validation rules for Count

	if len(errors) > 0 {
		return TagMultiError(errors)
	}

	return nil
}

// TagMultiError is an error wrapping multiple validation errors returned by
// Tag.ValidateAll() if the designated constraints aren't met.
type TagMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TagMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TagMultiError) AllErrors() []error { return m }

// TagValidationError is the validation error returned by Tag.Validate if the
// designated constraints aren't met.
type TagValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TagValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TagValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TagValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TagValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TagValidationError) ErrorName() string { return "TagValidationError" }

// Error satisfies the builtin error interface
func (e TagValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTag.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TagValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TagValidationError{}

// Validate checks the field values on GetHotTagsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetHotTagsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHotTagsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHotTagsRequestMultiError, or nil if none found.
func (m *GetHotTagsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHotTagsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Limit

	if len(errors) > 0 {
		return GetHotTagsRequestMultiError(errors)
	}

	return nil
}

// GetHotTagsRequestMultiError is an error wrapping multiple validation errors
// returned by GetHotTagsRequest.ValidateAll() if the designated constraints
// aren't met.
type GetHotTagsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHotTagsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHotTagsRequestMultiError) AllErrors() []error { return m }

// GetHotTagsRequestValidationError is the validation error returned by
// GetHotTagsRequest.Validate if the designated constraints aren't met.
type GetHotTagsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHotTagsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHotTagsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHotTagsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHotTagsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHotTagsRequestValidationError) ErrorName() string {
	return "GetHotTagsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetHotTagsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHotTagsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHotTagsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHotTagsRequestValidationError{}

// Validate checks the field values on GetHotTagsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetHotTagsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHotTagsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetHotTagsResponseMultiError, or nil if none found.
func (m *GetHotTagsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHotTagsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetTags() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetHotTagsResponseValidationError{
						field:  fmt.Sprintf("Tags[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetHotTagsResponseValidationError{
						field:  fmt.Sprintf("Tags[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetHotTagsResponseValidationError{
					field:  fmt.Sprintf("Tags[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetHotTagsResponseMultiError(errors)
	}

	return nil
}

// GetHotTagsResponseMultiError is an error wrapping multiple validation errors
// returned by GetHotTagsResponse.ValidateAll() if the designated constraints
// aren't met.
type GetHotTagsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHotTagsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHotTagsResponseMultiError) AllErrors() []error { return m }

// GetHotTagsResponseValidationError is the validation error returned by
// GetHotTagsResponse.Validate if the designated constraints aren't met.
type GetHotTagsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHotTagsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHotTagsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHotTagsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHotTagsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHotTagsResponseValidationError) ErrorName() string {
	return "GetHotTagsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetHotTagsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHotTagsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHotTagsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHotTagsResponseValidationError{}

// Validate checks the field values on GlobalSearchRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GlobalSearchRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GlobalSearchRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GlobalSearchRequestMultiError, or nil if none found.
func (m *GlobalSearchRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GlobalSearchRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Keyword

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GlobalSearchRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GlobalSearchRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GlobalSearchRequestValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GlobalSearchRequestMultiError(errors)
	}

	return nil
}

// GlobalSearchRequestMultiError is an error wrapping multiple validation
// errors returned by GlobalSearchRequest.ValidateAll() if the designated
// constraints aren't met.
type GlobalSearchRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GlobalSearchRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GlobalSearchRequestMultiError) AllErrors() []error { return m }

// GlobalSearchRequestValidationError is the validation error returned by
// GlobalSearchRequest.Validate if the designated constraints aren't met.
type GlobalSearchRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GlobalSearchRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GlobalSearchRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GlobalSearchRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GlobalSearchRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GlobalSearchRequestValidationError) ErrorName() string {
	return "GlobalSearchRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GlobalSearchRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGlobalSearchRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GlobalSearchRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GlobalSearchRequestValidationError{}

// Validate checks the field values on GlobalSearchResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GlobalSearchResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GlobalSearchResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GlobalSearchResponseMultiError, or nil if none found.
func (m *GlobalSearchResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GlobalSearchResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetUsers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Users[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GlobalSearchResponseValidationError{
					field:  fmt.Sprintf("Users[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetBlogs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Blogs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Blogs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GlobalSearchResponseValidationError{
					field:  fmt.Sprintf("Blogs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetAlbums() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Albums[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Albums[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GlobalSearchResponseValidationError{
					field:  fmt.Sprintf("Albums[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetShares() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Shares[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Shares[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GlobalSearchResponseValidationError{
					field:  fmt.Sprintf("Shares[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	for idx, item := range m.GetGroups() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GlobalSearchResponseValidationError{
						field:  fmt.Sprintf("Groups[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GlobalSearchResponseValidationError{
					field:  fmt.Sprintf("Groups[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GlobalSearchResponseMultiError(errors)
	}

	return nil
}

// GlobalSearchResponseMultiError is an error wrapping multiple validation
// errors returned by GlobalSearchResponse.ValidateAll() if the designated
// constraints aren't met.
type GlobalSearchResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GlobalSearchResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GlobalSearchResponseMultiError) AllErrors() []error { return m }

// GlobalSearchResponseValidationError is the validation error returned by
// GlobalSearchResponse.Validate if the designated constraints aren't met.
type GlobalSearchResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GlobalSearchResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GlobalSearchResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GlobalSearchResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GlobalSearchResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GlobalSearchResponseValidationError) ErrorName() string {
	return "GlobalSearchResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GlobalSearchResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGlobalSearchResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GlobalSearchResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GlobalSearchResponseValidationError{}
