// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: content/album.proto

package content

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

import google_protobuf2 "google.golang.org/protobuf/types/known/emptypb"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ======================
// AlbumService Interface
// ======================

// 相册服务
type AlbumService interface {
	CreateAlbum(context.Context, *CreateAlbumRequest) (*Album, error)

	GetAlbum(context.Context, *GetAlbumRequest) (*Album, error)

	UpdateAlbum(context.Context, *UpdateAlbumRequest) (*Album, error)

	DeleteAlbum(context.Context, *DeleteAlbumRequest) (*google_protobuf2.Empty, error)

	GetAlbums(context.Context, *GetAlbumsRequest) (*GetAlbumsResponse, error)

	UploadPhoto(context.Context, *UploadPhotoRequest) (*Photo, error)

	GetPhotos(context.Context, *GetPhotosRequest) (*GetPhotosResponse, error)

	DeletePhoto(context.Context, *DeletePhotoRequest) (*google_protobuf2.Empty, error)
}

// ============================
// AlbumService Protobuf Client
// ============================

type albumServiceProtobufClient struct {
	client      HTTPClient
	urls        [8]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAlbumServiceProtobufClient creates a Protobuf client that implements the AlbumService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAlbumServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AlbumService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "uchome.content", "AlbumService")
	urls := [8]string{
		serviceURL + "CreateAlbum",
		serviceURL + "GetAlbum",
		serviceURL + "UpdateAlbum",
		serviceURL + "DeleteAlbum",
		serviceURL + "GetAlbums",
		serviceURL + "UploadPhoto",
		serviceURL + "GetPhotos",
		serviceURL + "DeletePhoto",
	}

	return &albumServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *albumServiceProtobufClient) CreateAlbum(ctx context.Context, in *CreateAlbumRequest) (*Album, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateAlbum")
	caller := c.callCreateAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateAlbumRequest) (*Album, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAlbumRequest) when calling interceptor")
					}
					return c.callCreateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callCreateAlbum(ctx context.Context, in *CreateAlbumRequest) (*Album, error) {
	out := new(Album)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceProtobufClient) GetAlbum(ctx context.Context, in *GetAlbumRequest) (*Album, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbum")
	caller := c.callGetAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetAlbumRequest) (*Album, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumRequest) when calling interceptor")
					}
					return c.callGetAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callGetAlbum(ctx context.Context, in *GetAlbumRequest) (*Album, error) {
	out := new(Album)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceProtobufClient) UpdateAlbum(ctx context.Context, in *UpdateAlbumRequest) (*Album, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateAlbum")
	caller := c.callUpdateAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateAlbumRequest) (*Album, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateAlbumRequest) when calling interceptor")
					}
					return c.callUpdateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callUpdateAlbum(ctx context.Context, in *UpdateAlbumRequest) (*Album, error) {
	out := new(Album)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceProtobufClient) DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteAlbum")
	caller := c.callDeleteAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAlbumRequest) when calling interceptor")
					}
					return c.callDeleteAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callDeleteAlbum(ctx context.Context, in *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceProtobufClient) GetAlbums(ctx context.Context, in *GetAlbumsRequest) (*GetAlbumsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbums")
	caller := c.callGetAlbums
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetAlbumsRequest) (*GetAlbumsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumsRequest) when calling interceptor")
					}
					return c.callGetAlbums(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetAlbumsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetAlbumsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callGetAlbums(ctx context.Context, in *GetAlbumsRequest) (*GetAlbumsResponse, error) {
	out := new(GetAlbumsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceProtobufClient) UploadPhoto(ctx context.Context, in *UploadPhotoRequest) (*Photo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "UploadPhoto")
	caller := c.callUploadPhoto
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UploadPhotoRequest) (*Photo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UploadPhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UploadPhotoRequest) when calling interceptor")
					}
					return c.callUploadPhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Photo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Photo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callUploadPhoto(ctx context.Context, in *UploadPhotoRequest) (*Photo, error) {
	out := new(Photo)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceProtobufClient) GetPhotos(ctx context.Context, in *GetPhotosRequest) (*GetPhotosResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPhotos")
	caller := c.callGetPhotos
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPhotosRequest) (*GetPhotosResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhotosRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhotosRequest) when calling interceptor")
					}
					return c.callGetPhotos(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhotosResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhotosResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callGetPhotos(ctx context.Context, in *GetPhotosRequest) (*GetPhotosResponse, error) {
	out := new(GetPhotosResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[6], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceProtobufClient) DeletePhoto(ctx context.Context, in *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePhoto")
	caller := c.callDeletePhoto
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePhotoRequest) when calling interceptor")
					}
					return c.callDeletePhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceProtobufClient) callDeletePhoto(ctx context.Context, in *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[7], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ========================
// AlbumService JSON Client
// ========================

type albumServiceJSONClient struct {
	client      HTTPClient
	urls        [8]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAlbumServiceJSONClient creates a JSON client that implements the AlbumService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAlbumServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) AlbumService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "uchome.content", "AlbumService")
	urls := [8]string{
		serviceURL + "CreateAlbum",
		serviceURL + "GetAlbum",
		serviceURL + "UpdateAlbum",
		serviceURL + "DeleteAlbum",
		serviceURL + "GetAlbums",
		serviceURL + "UploadPhoto",
		serviceURL + "GetPhotos",
		serviceURL + "DeletePhoto",
	}

	return &albumServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *albumServiceJSONClient) CreateAlbum(ctx context.Context, in *CreateAlbumRequest) (*Album, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateAlbum")
	caller := c.callCreateAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateAlbumRequest) (*Album, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAlbumRequest) when calling interceptor")
					}
					return c.callCreateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callCreateAlbum(ctx context.Context, in *CreateAlbumRequest) (*Album, error) {
	out := new(Album)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceJSONClient) GetAlbum(ctx context.Context, in *GetAlbumRequest) (*Album, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbum")
	caller := c.callGetAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetAlbumRequest) (*Album, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumRequest) when calling interceptor")
					}
					return c.callGetAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callGetAlbum(ctx context.Context, in *GetAlbumRequest) (*Album, error) {
	out := new(Album)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceJSONClient) UpdateAlbum(ctx context.Context, in *UpdateAlbumRequest) (*Album, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "UpdateAlbum")
	caller := c.callUpdateAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UpdateAlbumRequest) (*Album, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateAlbumRequest) when calling interceptor")
					}
					return c.callUpdateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callUpdateAlbum(ctx context.Context, in *UpdateAlbumRequest) (*Album, error) {
	out := new(Album)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceJSONClient) DeleteAlbum(ctx context.Context, in *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteAlbum")
	caller := c.callDeleteAlbum
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAlbumRequest) when calling interceptor")
					}
					return c.callDeleteAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callDeleteAlbum(ctx context.Context, in *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceJSONClient) GetAlbums(ctx context.Context, in *GetAlbumsRequest) (*GetAlbumsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbums")
	caller := c.callGetAlbums
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetAlbumsRequest) (*GetAlbumsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumsRequest) when calling interceptor")
					}
					return c.callGetAlbums(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetAlbumsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetAlbumsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callGetAlbums(ctx context.Context, in *GetAlbumsRequest) (*GetAlbumsResponse, error) {
	out := new(GetAlbumsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceJSONClient) UploadPhoto(ctx context.Context, in *UploadPhotoRequest) (*Photo, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "UploadPhoto")
	caller := c.callUploadPhoto
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *UploadPhotoRequest) (*Photo, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UploadPhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UploadPhotoRequest) when calling interceptor")
					}
					return c.callUploadPhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Photo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Photo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callUploadPhoto(ctx context.Context, in *UploadPhotoRequest) (*Photo, error) {
	out := new(Photo)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[5], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceJSONClient) GetPhotos(ctx context.Context, in *GetPhotosRequest) (*GetPhotosResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "GetPhotos")
	caller := c.callGetPhotos
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetPhotosRequest) (*GetPhotosResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhotosRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhotosRequest) when calling interceptor")
					}
					return c.callGetPhotos(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhotosResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhotosResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callGetPhotos(ctx context.Context, in *GetPhotosRequest) (*GetPhotosResponse, error) {
	out := new(GetPhotosResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[6], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *albumServiceJSONClient) DeletePhoto(ctx context.Context, in *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithMethodName(ctx, "DeletePhoto")
	caller := c.callDeletePhoto
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePhotoRequest) when calling interceptor")
					}
					return c.callDeletePhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *albumServiceJSONClient) callDeletePhoto(ctx context.Context, in *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[7], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===========================
// AlbumService Server Handler
// ===========================

type albumServiceServer struct {
	AlbumService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewAlbumServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewAlbumServiceServer(svc AlbumService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &albumServiceServer{
		AlbumService:     svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *albumServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *albumServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// AlbumServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const AlbumServicePathPrefix = "/twirp/uchome.content.AlbumService/"

func (s *albumServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "AlbumService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "uchome.content.AlbumService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CreateAlbum":
		s.serveCreateAlbum(ctx, resp, req)
		return
	case "GetAlbum":
		s.serveGetAlbum(ctx, resp, req)
		return
	case "UpdateAlbum":
		s.serveUpdateAlbum(ctx, resp, req)
		return
	case "DeleteAlbum":
		s.serveDeleteAlbum(ctx, resp, req)
		return
	case "GetAlbums":
		s.serveGetAlbums(ctx, resp, req)
		return
	case "UploadPhoto":
		s.serveUploadPhoto(ctx, resp, req)
		return
	case "GetPhotos":
		s.serveGetPhotos(ctx, resp, req)
		return
	case "DeletePhoto":
		s.serveDeletePhoto(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *albumServiceServer) serveCreateAlbum(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateAlbumJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateAlbumProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveCreateAlbumJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateAlbumRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.CreateAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateAlbumRequest) (*Album, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.CreateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Album
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Album and nil error while calling CreateAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveCreateAlbumProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateAlbumRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.CreateAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateAlbumRequest) (*Album, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.CreateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Album
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Album and nil error while calling CreateAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveGetAlbum(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetAlbumJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetAlbumProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveGetAlbumJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetAlbumRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.GetAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetAlbumRequest) (*Album, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.GetAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Album
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Album and nil error while calling GetAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveGetAlbumProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetAlbumRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.GetAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetAlbumRequest) (*Album, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.GetAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Album
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Album and nil error while calling GetAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveUpdateAlbum(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUpdateAlbumJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUpdateAlbumProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveUpdateAlbumJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UpdateAlbumRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.UpdateAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateAlbumRequest) (*Album, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.UpdateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Album
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Album and nil error while calling UpdateAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveUpdateAlbumProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UpdateAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UpdateAlbumRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.UpdateAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UpdateAlbumRequest) (*Album, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UpdateAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UpdateAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.UpdateAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Album)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Album) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Album
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Album and nil error while calling UpdateAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveDeleteAlbum(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteAlbumJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteAlbumProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveDeleteAlbumJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteAlbumRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.DeleteAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.DeleteAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling DeleteAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveDeleteAlbumProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteAlbum")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteAlbumRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.DeleteAlbum
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteAlbumRequest) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteAlbumRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteAlbumRequest) when calling interceptor")
					}
					return s.AlbumService.DeleteAlbum(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling DeleteAlbum. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveGetAlbums(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetAlbumsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetAlbumsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveGetAlbumsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbums")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetAlbumsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.GetAlbums
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetAlbumsRequest) (*GetAlbumsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumsRequest) when calling interceptor")
					}
					return s.AlbumService.GetAlbums(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetAlbumsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetAlbumsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetAlbumsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetAlbumsResponse and nil error while calling GetAlbums. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveGetAlbumsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetAlbums")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetAlbumsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.GetAlbums
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetAlbumsRequest) (*GetAlbumsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetAlbumsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetAlbumsRequest) when calling interceptor")
					}
					return s.AlbumService.GetAlbums(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetAlbumsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetAlbumsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetAlbumsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetAlbumsResponse and nil error while calling GetAlbums. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveUploadPhoto(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveUploadPhotoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveUploadPhotoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveUploadPhotoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UploadPhoto")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(UploadPhotoRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.UploadPhoto
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UploadPhotoRequest) (*Photo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UploadPhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UploadPhotoRequest) when calling interceptor")
					}
					return s.AlbumService.UploadPhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Photo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Photo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Photo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Photo and nil error while calling UploadPhoto. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveUploadPhotoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "UploadPhoto")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(UploadPhotoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.UploadPhoto
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *UploadPhotoRequest) (*Photo, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*UploadPhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*UploadPhotoRequest) when calling interceptor")
					}
					return s.AlbumService.UploadPhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Photo)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Photo) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Photo
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Photo and nil error while calling UploadPhoto. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveGetPhotos(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetPhotosJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetPhotosProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveGetPhotosJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPhotos")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetPhotosRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.GetPhotos
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPhotosRequest) (*GetPhotosResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhotosRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhotosRequest) when calling interceptor")
					}
					return s.AlbumService.GetPhotos(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhotosResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhotosResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPhotosResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPhotosResponse and nil error while calling GetPhotos. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveGetPhotosProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetPhotos")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetPhotosRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.GetPhotos
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetPhotosRequest) (*GetPhotosResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetPhotosRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetPhotosRequest) when calling interceptor")
					}
					return s.AlbumService.GetPhotos(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetPhotosResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetPhotosResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetPhotosResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetPhotosResponse and nil error while calling GetPhotos. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveDeletePhoto(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeletePhotoJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeletePhotoProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *albumServiceServer) serveDeletePhotoJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePhoto")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeletePhotoRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.AlbumService.DeletePhoto
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePhotoRequest) when calling interceptor")
					}
					return s.AlbumService.DeletePhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling DeletePhoto. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) serveDeletePhotoProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeletePhoto")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeletePhotoRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.AlbumService.DeletePhoto
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeletePhotoRequest) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeletePhotoRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeletePhotoRequest) when calling interceptor")
					}
					return s.AlbumService.DeletePhoto(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling DeletePhoto. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *albumServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *albumServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *albumServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "uchome.content", "AlbumService")
}

var twirpFileDescriptor1 = []byte{
	// 959 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x8e, 0xdb, 0x54,
	0x10, 0x96, 0x93, 0x38, 0xd9, 0x8c, 0x97, 0xdd, 0xf6, 0xc0, 0xb6, 0xae, 0x5b, 0xb4, 0x59, 0x4b,
	0x88, 0xd5, 0x8a, 0xc6, 0x10, 0x7e, 0xa4, 0x96, 0xab, 0xa5, 0x20, 0xb4, 0x12, 0x17, 0x95, 0xa1,
	0x37, 0xdc, 0x44, 0x8e, 0x7d, 0x1a, 0x9b, 0x8d, 0x7d, 0x8c, 0x7d, 0x9c, 0xd5, 0xaa, 0xea, 0x0d,
	0x12, 0x0f, 0x80, 0xb8, 0xe3, 0x92, 0x17, 0xe0, 0x09, 0x10, 0x0f, 0xc1, 0x2b, 0xf0, 0x20, 0xe8,
	0xfc, 0x25, 0xfe, 0x89, 0x93, 0x54, 0x70, 0xb3, 0xeb, 0x33, 0x33, 0x3e, 0x33, 0xf3, 0x7d, 0xdf,
	0x4c, 0x0c, 0x6f, 0xfb, 0x24, 0xa1, 0x38, 0xa1, 0x8e, 0xb7, 0x98, 0x15, 0xf1, 0x38, 0xcd, 0x08,
	0x25, 0xe8, 0xa8, 0xf0, 0x43, 0x12, 0xe3, 0xb1, 0xf4, 0x59, 0x8f, 0xe6, 0x84, 0xcc, 0x17, 0xd8,
	0xf1, 0xd2, 0xc8, 0xf1, 0x92, 0x84, 0x50, 0x8f, 0x46, 0x24, 0xc9, 0x45, 0xb4, 0x75, 0x2a, 0xbd,
	0xfc, 0x34, 0x2b, 0x5e, 0x3a, 0x34, 0x8a, 0x71, 0x4e, 0xbd, 0x38, 0x95, 0x01, 0x0f, 0xeb, 0x01,
	0x38, 0x4e, 0xe9, 0xad, 0x74, 0x22, 0x9f, 0xc4, 0x31, 0x49, 0x1c, 0x7a, 0x9b, 0x62, 0x75, 0xe3,
	0x71, 0x91, 0xe3, 0xcc, 0x61, 0x7f, 0x84, 0xc1, 0xfe, 0xa5, 0x03, 0xfa, 0xf3, 0x90, 0x95, 0xf6,
	0x00, 0x0e, 0x52, 0xf6, 0x30, 0x8d, 0x02, 0x53, 0x1b, 0x69, 0xe7, 0x43, 0x77, 0xc0, 0xcf, 0x57,
	0x01, 0x73, 0xf1, 0x26, 0x98, 0xab, 0x23, 0x5c, 0xfc, 0x7c, 0x15, 0xa0, 0xfb, 0x30, 0x60, 0xb7,
	0x31, 0x4f, 0x97, 0x7b, 0xfa, 0xec, 0x78, 0x15, 0xa0, 0x3b, 0xd0, 0x2d, 0xb2, 0x85, 0xd9, 0xe3,
	0x46, 0xf6, 0x88, 0x1e, 0xc1, 0x90, 0x86, 0x45, 0x3c, 0x4b, 0xbc, 0x68, 0x61, 0xea, 0xdc, 0xbe,
	0x36, 0xa0, 0x11, 0x18, 0x01, 0xce, 0xfd, 0x2c, 0x4a, 0x19, 0x02, 0x66, 0x9f, 0xfb, 0xcb, 0x26,
	0xf4, 0x0e, 0xe8, 0x37, 0x51, 0x40, 0x43, 0x73, 0x30, 0xd2, 0xce, 0x75, 0x57, 0x1c, 0xd0, 0x3d,
	0xe8, 0x87, 0x38, 0x9a, 0x87, 0xd4, 0x3c, 0xe0, 0x66, 0x79, 0x42, 0x4f, 0x00, 0xfc, 0x0c, 0x7b,
	0x14, 0x07, 0x53, 0x8f, 0x9a, 0xc3, 0x91, 0x76, 0x6e, 0x4c, 0xac, 0xb1, 0xc0, 0x6b, 0xac, 0xf0,
	0x1a, 0x7f, 0xa7, 0x00, 0x75, 0x87, 0x32, 0xfa, 0x92, 0xda, 0xbf, 0x75, 0x41, 0xbf, 0x64, 0xfd,
	0x55, 0x1a, 0xd7, 0x5a, 0x1b, 0xef, 0x54, 0x1a, 0x47, 0xd0, 0x4b, 0xbc, 0x18, 0x4b, 0x38, 0xf8,
	0x73, 0xbd, 0xb9, 0x5e, 0xb3, 0xb9, 0x53, 0x30, 0x7c, 0xb2, 0xc4, 0xd9, 0x94, 0x63, 0x2e, 0xe1,
	0x01, 0x6e, 0x12, 0xf4, 0x7c, 0x0a, 0x83, 0x34, 0x8b, 0x96, 0x9e, 0x7f, 0xcb, 0xb1, 0x39, 0x9a,
	0x3c, 0x1c, 0xaf, 0xb4, 0xc4, 0x68, 0x1e, 0x3f, 0x17, 0xde, 0x6f, 0xf0, 0x12, 0x2f, 0x5c, 0x15,
	0x5b, 0x83, 0x61, 0xf0, 0x06, 0x30, 0xb0, 0x57, 0x8b, 0x34, 0x50, 0xaf, 0x1e, 0xec, 0x7e, 0x55,
	0x46, 0x5f, 0x52, 0xf4, 0x3e, 0xe8, 0xe4, 0x26, 0xc1, 0x99, 0xc4, 0xfd, 0xae, 0x2a, 0x95, 0x0b,
	0xef, 0x45, 0x8e, 0x33, 0x57, 0xf8, 0xd1, 0x87, 0xa0, 0xe7, 0xd4, 0xa3, 0xb9, 0x09, 0xf2, 0xfa,
	0xea, 0x7c, 0x8c, 0x39, 0x0d, 0xdf, 0xb2, 0x08, 0x57, 0x04, 0xda, 0x37, 0x00, 0x6b, 0x23, 0x3a,
	0x83, 0x43, 0x0e, 0x58, 0x3e, 0xf5, 0x49, 0x91, 0x50, 0x4e, 0x92, 0xee, 0x1a, 0xc2, 0xf6, 0x8c,
	0x99, 0x18, 0xb2, 0xcb, 0x08, 0xdf, 0xa8, 0x88, 0x0e, 0x8f, 0x00, 0x6e, 0x12, 0x01, 0xef, 0xc1,
	0x11, 0x83, 0x10, 0x27, 0x54, 0xc5, 0x74, 0x79, 0xcc, 0x5b, 0xca, 0xca, 0xc3, 0xec, 0xdf, 0x35,
	0x40, 0xcf, 0x38, 0x38, 0x3c, 0xbf, 0x8b, 0x7f, 0x2c, 0x70, 0x4e, 0x57, 0x74, 0x6b, 0xed, 0x74,
	0x77, 0x76, 0xd2, 0xdd, 0xdd, 0x46, 0x77, 0x6f, 0x7f, 0xba, 0xed, 0x3f, 0x35, 0x40, 0x2f, 0x38,
	0x0d, 0x95, 0x22, 0xb7, 0xe8, 0x58, 0xd5, 0xdf, 0x69, 0xaf, 0xbf, 0xbb, 0xb3, 0xfe, 0xde, 0xb6,
	0xfa, 0xf5, 0x37, 0xa8, 0xff, 0x25, 0xdc, 0xf9, 0x1a, 0x53, 0x5e, 0x7b, 0xae, 0x8a, 0x2f, 0x4d,
	0x9a, 0x56, 0x99, 0xb4, 0x27, 0x00, 0xa9, 0x37, 0x8f, 0x12, 0x6f, 0x85, 0xb2, 0x31, 0x79, 0x50,
	0x4f, 0xb3, 0x0a, 0x70, 0x4b, 0xc1, 0xf6, 0xcf, 0x1a, 0xdc, 0x2d, 0x25, 0xca, 0x53, 0x92, 0xe4,
	0x18, 0x3d, 0x86, 0x3e, 0x87, 0x25, 0x37, 0xb5, 0x51, 0xf7, 0xdc, 0x98, 0x9c, 0x6c, 0x94, 0xa3,
	0x2b, 0x83, 0xd0, 0xe5, 0x86, 0xfc, 0x67, 0xed, 0xf9, 0x65, 0x96, 0x4a, 0x1d, 0x1f, 0xc0, 0xb1,
	0x2a, 0x63, 0x37, 0x57, 0xb6, 0x03, 0xe8, 0x4b, 0xbc, 0xc0, 0x7b, 0x93, 0x6b, 0xff, 0xc1, 0xe5,
	0xb0, 0x20, 0x5e, 0xc0, 0x59, 0xd9, 0x43, 0x0e, 0x72, 0x6d, 0x77, 0x5a, 0xd6, 0x76, 0x77, 0xc7,
	0xda, 0xee, 0x6d, 0x59, 0xdb, 0xfa, 0xe6, 0xb5, 0xdd, 0x2f, 0xaf, 0x6d, 0x3b, 0xe4, 0x02, 0xe0,
	0xd5, 0xe6, 0x7b, 0x94, 0xfb, 0xdf, 0x25, 0xa0, 0x52, 0xad, 0x25, 0x20, 0x96, 0x47, 0x9b, 0x04,
	0x04, 0x90, 0x32, 0xe8, 0xff, 0x90, 0xc0, 0x8a, 0xd4, 0x3a, 0x45, 0x2d, 0xbf, 0xc6, 0x93, 0xbf,
	0xfa, 0x70, 0x28, 0x56, 0x20, 0xce, 0x96, 0x91, 0x8f, 0xd1, 0x14, 0x8c, 0xd2, 0x62, 0x42, 0x76,
	0xbd, 0xe4, 0xe6, 0xd6, 0xb2, 0x36, 0x2b, 0xdb, 0x3e, 0xf9, 0xe9, 0xef, 0x7f, 0x7e, 0xed, 0x1c,
	0x3f, 0xd5, 0x2e, 0x6c, 0x70, 0x96, 0x1f, 0x39, 0x52, 0xe8, 0x1e, 0x1c, 0x28, 0x95, 0xa2, 0xd3,
	0xfa, 0x9b, 0x35, 0xfd, 0xb6, 0x5d, 0xfd, 0x2e, 0xbf, 0xfa, 0x3e, 0x3a, 0x59, 0xdf, 0xeb, 0xbc,
	0x52, 0xb4, 0xbe, 0x46, 0x3f, 0x80, 0x51, 0xda, 0x5b, 0xcd, 0x1e, 0x9a, 0x4b, 0xad, 0x2d, 0xd1,
	0x88, 0x27, 0xb2, 0x9e, 0x6a, 0x17, 0x56, 0x4b, 0xae, 0x10, 0x8c, 0xd2, 0x18, 0x35, 0x73, 0x35,
	0x67, 0xcc, 0xba, 0xd7, 0xf8, 0xdd, 0xfb, 0x8a, 0x7d, 0x69, 0xa9, 0xae, 0x2e, 0x5a, 0x32, 0x05,
	0x30, 0x5c, 0x6d, 0x19, 0x34, 0x6a, 0x43, 0x4e, 0x09, 0xdd, 0x3a, 0xdb, 0x12, 0x21, 0x94, 0x63,
	0x23, 0x9e, 0xf0, 0x10, 0x95, 0xe9, 0x99, 0x32, 0xec, 0x56, 0x43, 0xbe, 0x09, 0xbb, 0xfa, 0x06,
	0xb0, 0x36, 0xcb, 0xba, 0xc1, 0xbf, 0x54, 0xb9, 0x68, 0x43, 0x4c, 0xca, 0xc6, 0x36, 0x2a, 0xf3,
	0xba, 0xb1, 0x8d, 0xea, 0x98, 0x55, 0xdb, 0x90, 0x59, 0x56, 0xb4, 0xb4, 0xb4, 0xd1, 0x9c, 0x92,
	0xfd, 0x68, 0x11, 0xd7, 0x3b, 0xaf, 0xd4, 0x3c, 0xbd, 0xfe, 0xe2, 0xb3, 0xef, 0x3f, 0x99, 0x47,
	0x34, 0x2c, 0x66, 0x6c, 0x44, 0x9d, 0x6b, 0x92, 0xcc, 0xaf, 0x71, 0xe2, 0xcc, 0xc9, 0x63, 0x96,
	0xcf, 0x49, 0xaf, 0xe7, 0xe2, 0x83, 0xda, 0x91, 0x99, 0x3f, 0x97, 0xff, 0x67, 0x7d, 0x6e, 0xfe,
	0xf8, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0xa9, 0x72, 0x73, 0xdb, 0x0b, 0x00, 0x00,
}
