// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: content/blog.proto

package content

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	common "github.com/kongken/go-home/pkg/proto/common"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = common.PrivacyLevel(0)
)

// Validate checks the field values on Blog with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Blog) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Blog with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in BlogMultiError, or nil if none found.
func (m *Blog) ValidateAll() error {
	return m.validate(true)
}

func (m *Blog) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BlogId

	// no validation rules for UserId

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Summary

	// no validation rules for CoverImage

	// no validation rules for Category

	// no validation rules for Privacy

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BlogValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BlogValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAuthor()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "Author",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "Author",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAuthor()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BlogValidationError{
				field:  "Author",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStats()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "Stats",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BlogValidationError{
					field:  "Stats",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStats()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BlogValidationError{
				field:  "Stats",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BlogMultiError(errors)
	}

	return nil
}

// BlogMultiError is an error wrapping multiple validation errors returned by
// Blog.ValidateAll() if the designated constraints aren't met.
type BlogMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BlogMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BlogMultiError) AllErrors() []error { return m }

// BlogValidationError is the validation error returned by Blog.Validate if the
// designated constraints aren't met.
type BlogValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BlogValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BlogValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BlogValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BlogValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BlogValidationError) ErrorName() string { return "BlogValidationError" }

// Error satisfies the builtin error interface
func (e BlogValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBlog.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BlogValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BlogValidationError{}

// Validate checks the field values on BlogStats with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BlogStats) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BlogStats with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BlogStatsMultiError, or nil
// if none found.
func (m *BlogStats) ValidateAll() error {
	return m.validate(true)
}

func (m *BlogStats) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ViewsCount

	// no validation rules for LikesCount

	// no validation rules for CommentsCount

	// no validation rules for FavoritesCount

	if len(errors) > 0 {
		return BlogStatsMultiError(errors)
	}

	return nil
}

// BlogStatsMultiError is an error wrapping multiple validation errors returned
// by BlogStats.ValidateAll() if the designated constraints aren't met.
type BlogStatsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BlogStatsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BlogStatsMultiError) AllErrors() []error { return m }

// BlogStatsValidationError is the validation error returned by
// BlogStats.Validate if the designated constraints aren't met.
type BlogStatsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BlogStatsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BlogStatsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BlogStatsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BlogStatsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BlogStatsValidationError) ErrorName() string { return "BlogStatsValidationError" }

// Error satisfies the builtin error interface
func (e BlogStatsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBlogStats.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BlogStatsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BlogStatsValidationError{}

// Validate checks the field values on CreateBlogRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateBlogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBlogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBlogRequestMultiError, or nil if none found.
func (m *CreateBlogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBlogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Summary

	// no validation rules for CoverImage

	// no validation rules for Category

	// no validation rules for Privacy

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateBlogRequestMultiError(errors)
	}

	return nil
}

// CreateBlogRequestMultiError is an error wrapping multiple validation errors
// returned by CreateBlogRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateBlogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBlogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBlogRequestMultiError) AllErrors() []error { return m }

// CreateBlogRequestValidationError is the validation error returned by
// CreateBlogRequest.Validate if the designated constraints aren't met.
type CreateBlogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBlogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBlogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBlogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBlogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBlogRequestValidationError) ErrorName() string {
	return "CreateBlogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBlogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBlogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBlogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBlogRequestValidationError{}

// Validate checks the field values on UpdateBlogRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateBlogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateBlogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateBlogRequestMultiError, or nil if none found.
func (m *UpdateBlogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateBlogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BlogId

	// no validation rules for Title

	// no validation rules for Content

	// no validation rules for Summary

	// no validation rules for CoverImage

	// no validation rules for Category

	// no validation rules for Privacy

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateBlogRequestMultiError(errors)
	}

	return nil
}

// UpdateBlogRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateBlogRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateBlogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateBlogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateBlogRequestMultiError) AllErrors() []error { return m }

// UpdateBlogRequestValidationError is the validation error returned by
// UpdateBlogRequest.Validate if the designated constraints aren't met.
type UpdateBlogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateBlogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateBlogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateBlogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateBlogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateBlogRequestValidationError) ErrorName() string {
	return "UpdateBlogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateBlogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateBlogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateBlogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateBlogRequestValidationError{}

// Validate checks the field values on GetBlogsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBlogsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBlogsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBlogsRequestMultiError, or nil if none found.
func (m *GetBlogsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBlogsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Category

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetBlogsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetBlogsRequestValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBlogsRequestValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetBlogsRequestMultiError(errors)
	}

	return nil
}

// GetBlogsRequestMultiError is an error wrapping multiple validation errors
// returned by GetBlogsRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBlogsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBlogsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBlogsRequestMultiError) AllErrors() []error { return m }

// GetBlogsRequestValidationError is the validation error returned by
// GetBlogsRequest.Validate if the designated constraints aren't met.
type GetBlogsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBlogsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBlogsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBlogsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBlogsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBlogsRequestValidationError) ErrorName() string { return "GetBlogsRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetBlogsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBlogsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBlogsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBlogsRequestValidationError{}

// Validate checks the field values on GetBlogsResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBlogsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBlogsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBlogsResponseMultiError, or nil if none found.
func (m *GetBlogsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBlogsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBlogs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetBlogsResponseValidationError{
						field:  fmt.Sprintf("Blogs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetBlogsResponseValidationError{
						field:  fmt.Sprintf("Blogs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetBlogsResponseValidationError{
					field:  fmt.Sprintf("Blogs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if all {
		switch v := interface{}(m.GetPagination()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetBlogsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetBlogsResponseValidationError{
					field:  "Pagination",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPagination()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetBlogsResponseValidationError{
				field:  "Pagination",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetBlogsResponseMultiError(errors)
	}

	return nil
}

// GetBlogsResponseMultiError is an error wrapping multiple validation errors
// returned by GetBlogsResponse.ValidateAll() if the designated constraints
// aren't met.
type GetBlogsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBlogsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBlogsResponseMultiError) AllErrors() []error { return m }

// GetBlogsResponseValidationError is the validation error returned by
// GetBlogsResponse.Validate if the designated constraints aren't met.
type GetBlogsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBlogsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBlogsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBlogsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBlogsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBlogsResponseValidationError) ErrorName() string { return "GetBlogsResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetBlogsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBlogsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBlogsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBlogsResponseValidationError{}

// Validate checks the field values on GetBlogRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetBlogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBlogRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetBlogRequestMultiError,
// or nil if none found.
func (m *GetBlogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBlogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BlogId

	if len(errors) > 0 {
		return GetBlogRequestMultiError(errors)
	}

	return nil
}

// GetBlogRequestMultiError is an error wrapping multiple validation errors
// returned by GetBlogRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBlogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBlogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBlogRequestMultiError) AllErrors() []error { return m }

// GetBlogRequestValidationError is the validation error returned by
// GetBlogRequest.Validate if the designated constraints aren't met.
type GetBlogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBlogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBlogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBlogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBlogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBlogRequestValidationError) ErrorName() string { return "GetBlogRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetBlogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBlogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBlogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBlogRequestValidationError{}

// Validate checks the field values on DeleteBlogRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DeleteBlogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteBlogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteBlogRequestMultiError, or nil if none found.
func (m *DeleteBlogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteBlogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BlogId

	if len(errors) > 0 {
		return DeleteBlogRequestMultiError(errors)
	}

	return nil
}

// DeleteBlogRequestMultiError is an error wrapping multiple validation errors
// returned by DeleteBlogRequest.ValidateAll() if the designated constraints
// aren't met.
type DeleteBlogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteBlogRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteBlogRequestMultiError) AllErrors() []error { return m }

// DeleteBlogRequestValidationError is the validation error returned by
// DeleteBlogRequest.Validate if the designated constraints aren't met.
type DeleteBlogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteBlogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteBlogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteBlogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteBlogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteBlogRequestValidationError) ErrorName() string {
	return "DeleteBlogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteBlogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteBlogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteBlogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteBlogRequestValidationError{}
