// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: content/comment.proto

package content

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

import google_protobuf2 "google.golang.org/protobuf/types/known/emptypb"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// ========================
// CommentService Interface
// ========================

// 评论服务
type CommentService interface {
	// 创建评论
	CreateComment(context.Context, *CreateCommentRequest) (*Comment, error)

	// 获取评论列表
	GetComments(context.Context, *GetCommentsRequest) (*GetCommentsResponse, error)

	// 删除评论
	DeleteComment(context.Context, *DeleteCommentRequest) (*google_protobuf2.Empty, error)
}

// ==============================
// CommentService Protobuf Client
// ==============================

type commentServiceProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewCommentServiceProtobufClient creates a Protobuf client that implements the CommentService interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewCommentServiceProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) CommentService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "uchome.content", "CommentService")
	urls := [3]string{
		serviceURL + "CreateComment",
		serviceURL + "GetComments",
		serviceURL + "DeleteComment",
	}

	return &commentServiceProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *commentServiceProtobufClient) CreateComment(ctx context.Context, in *CreateCommentRequest) (*Comment, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "CommentService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateComment")
	caller := c.callCreateComment
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateCommentRequest) (*Comment, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateCommentRequest) when calling interceptor")
					}
					return c.callCreateComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Comment)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Comment) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *commentServiceProtobufClient) callCreateComment(ctx context.Context, in *CreateCommentRequest) (*Comment, error) {
	out := new(Comment)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *commentServiceProtobufClient) GetComments(ctx context.Context, in *GetCommentsRequest) (*GetCommentsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "CommentService")
	ctx = ctxsetters.WithMethodName(ctx, "GetComments")
	caller := c.callGetComments
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetCommentsRequest) (*GetCommentsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetCommentsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetCommentsRequest) when calling interceptor")
					}
					return c.callGetComments(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetCommentsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetCommentsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *commentServiceProtobufClient) callGetComments(ctx context.Context, in *GetCommentsRequest) (*GetCommentsResponse, error) {
	out := new(GetCommentsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *commentServiceProtobufClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "CommentService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	caller := c.callDeleteComment
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteCommentRequest) when calling interceptor")
					}
					return c.callDeleteComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *commentServiceProtobufClient) callDeleteComment(ctx context.Context, in *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==========================
// CommentService JSON Client
// ==========================

type commentServiceJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewCommentServiceJSONClient creates a JSON client that implements the CommentService interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewCommentServiceJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) CommentService {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "uchome.content", "CommentService")
	urls := [3]string{
		serviceURL + "CreateComment",
		serviceURL + "GetComments",
		serviceURL + "DeleteComment",
	}

	return &commentServiceJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *commentServiceJSONClient) CreateComment(ctx context.Context, in *CreateCommentRequest) (*Comment, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "CommentService")
	ctx = ctxsetters.WithMethodName(ctx, "CreateComment")
	caller := c.callCreateComment
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *CreateCommentRequest) (*Comment, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateCommentRequest) when calling interceptor")
					}
					return c.callCreateComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Comment)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Comment) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *commentServiceJSONClient) callCreateComment(ctx context.Context, in *CreateCommentRequest) (*Comment, error) {
	out := new(Comment)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *commentServiceJSONClient) GetComments(ctx context.Context, in *GetCommentsRequest) (*GetCommentsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "CommentService")
	ctx = ctxsetters.WithMethodName(ctx, "GetComments")
	caller := c.callGetComments
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetCommentsRequest) (*GetCommentsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetCommentsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetCommentsRequest) when calling interceptor")
					}
					return c.callGetComments(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetCommentsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetCommentsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *commentServiceJSONClient) callGetComments(ctx context.Context, in *GetCommentsRequest) (*GetCommentsResponse, error) {
	out := new(GetCommentsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *commentServiceJSONClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "CommentService")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	caller := c.callDeleteComment
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteCommentRequest) when calling interceptor")
					}
					return c.callDeleteComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *commentServiceJSONClient) callDeleteComment(ctx context.Context, in *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
	out := new(google_protobuf2.Empty)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =============================
// CommentService Server Handler
// =============================

type commentServiceServer struct {
	CommentService
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewCommentServiceServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewCommentServiceServer(svc CommentService, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &commentServiceServer{
		CommentService:   svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *commentServiceServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *commentServiceServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// CommentServicePathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const CommentServicePathPrefix = "/twirp/uchome.content.CommentService/"

func (s *commentServiceServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "uchome.content")
	ctx = ctxsetters.WithServiceName(ctx, "CommentService")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "uchome.content.CommentService" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "CreateComment":
		s.serveCreateComment(ctx, resp, req)
		return
	case "GetComments":
		s.serveGetComments(ctx, resp, req)
		return
	case "DeleteComment":
		s.serveDeleteComment(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *commentServiceServer) serveCreateComment(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateCommentJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateCommentProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *commentServiceServer) serveCreateCommentJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(CreateCommentRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.CommentService.CreateComment
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateCommentRequest) (*Comment, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateCommentRequest) when calling interceptor")
					}
					return s.CommentService.CreateComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Comment)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Comment) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Comment
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Comment and nil error while calling CreateComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *commentServiceServer) serveCreateCommentProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(CreateCommentRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.CommentService.CreateComment
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *CreateCommentRequest) (*Comment, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*CreateCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*CreateCommentRequest) when calling interceptor")
					}
					return s.CommentService.CreateComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*Comment)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*Comment) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *Comment
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *Comment and nil error while calling CreateComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *commentServiceServer) serveGetComments(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetCommentsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetCommentsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *commentServiceServer) serveGetCommentsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetComments")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetCommentsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.CommentService.GetComments
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetCommentsRequest) (*GetCommentsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetCommentsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetCommentsRequest) when calling interceptor")
					}
					return s.CommentService.GetComments(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetCommentsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetCommentsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetCommentsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetCommentsResponse and nil error while calling GetComments. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *commentServiceServer) serveGetCommentsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetComments")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetCommentsRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.CommentService.GetComments
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetCommentsRequest) (*GetCommentsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetCommentsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetCommentsRequest) when calling interceptor")
					}
					return s.CommentService.GetComments(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetCommentsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetCommentsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetCommentsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetCommentsResponse and nil error while calling GetComments. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *commentServiceServer) serveDeleteComment(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteCommentJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteCommentProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *commentServiceServer) serveDeleteCommentJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(DeleteCommentRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.CommentService.DeleteComment
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteCommentRequest) when calling interceptor")
					}
					return s.CommentService.DeleteComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling DeleteComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *commentServiceServer) serveDeleteCommentProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(DeleteCommentRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.CommentService.DeleteComment
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *DeleteCommentRequest) (*google_protobuf2.Empty, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*DeleteCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*DeleteCommentRequest) when calling interceptor")
					}
					return s.CommentService.DeleteComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*google_protobuf2.Empty)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*google_protobuf2.Empty) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *google_protobuf2.Empty
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *google_protobuf2.Empty and nil error while calling DeleteComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *commentServiceServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor3, 0
}

func (s *commentServiceServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *commentServiceServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "uchome.content", "CommentService")
}

var twirpFileDescriptor3 = []byte{
	// 649 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xc1, 0x4f, 0xd4, 0x4e,
	0x14, 0x4e, 0x77, 0x81, 0x65, 0x5f, 0x81, 0x5f, 0x98, 0x1f, 0x4a, 0x59, 0x54, 0x96, 0xa2, 0xc9,
	0x86, 0xc4, 0x4e, 0x58, 0xd4, 0x04, 0xbd, 0x88, 0x68, 0xcc, 0x1e, 0x4c, 0x4c, 0xc5, 0x8b, 0x17,
	0x52, 0xda, 0x67, 0x69, 0x76, 0xb7, 0x33, 0x76, 0xa6, 0x24, 0xc4, 0x78, 0xf1, 0xee, 0xc9, 0xbf,
	0xcb, 0x13, 0x27, 0xef, 0xfe, 0x21, 0x66, 0xa6, 0xd3, 0x75, 0xcb, 0x42, 0x13, 0x13, 0x2f, 0xbb,
	0x99, 0xf7, 0xbe, 0x99, 0xef, 0x7b, 0xdf, 0xd7, 0x19, 0xb8, 0x15, 0xb2, 0x54, 0x62, 0x2a, 0x69,
	0xc8, 0xc6, 0x63, 0x4c, 0xa5, 0xc7, 0x33, 0x26, 0x19, 0x59, 0xc9, 0xc3, 0x33, 0x36, 0x46, 0xcf,
	0x74, 0x3b, 0x77, 0x62, 0xc6, 0xe2, 0x11, 0xd2, 0x80, 0x27, 0x34, 0x48, 0x53, 0x26, 0x03, 0x99,
	0xb0, 0x54, 0x14, 0xe8, 0xce, 0x96, 0xe9, 0xea, 0xd5, 0x69, 0xfe, 0x91, 0xca, 0x64, 0x8c, 0x42,
	0x06, 0x63, 0x6e, 0x00, 0x9b, 0x57, 0x01, 0x38, 0xe6, 0xf2, 0xc2, 0x34, 0x89, 0xa2, 0x66, 0x29,
	0x95, 0x17, 0x1c, 0xcb, 0x13, 0xff, 0xcb, 0x05, 0x66, 0x54, 0xfd, 0x14, 0x05, 0xf7, 0xb2, 0x09,
	0xad, 0xa3, 0x42, 0x22, 0xb9, 0x0b, 0x60, 0xd4, 0x9e, 0x24, 0x91, 0x63, 0x75, 0xad, 0x5e, 0xdb,
	0x6f, 0x9b, 0xca, 0x20, 0x22, 0xeb, 0xd0, 0x52, 0x1b, 0x55, 0xaf, 0xa1, 0x7b, 0x0b, 0x6a, 0x39,
	0x88, 0xc8, 0x26, 0xb4, 0x65, 0x90, 0xc5, 0xa8, 0xb7, 0x35, 0x75, 0x6b, 0xb1, 0x28, 0x0c, 0x22,
	0xb2, 0x05, 0xb6, 0x69, 0x2a, 0x1d, 0xce, 0x9c, 0x6e, 0x43, 0x51, 0x3a, 0xbe, 0xe0, 0x48, 0x1c,
	0x68, 0x19, 0x37, 0x9c, 0x79, 0xdd, 0x2c, 0x97, 0xea, 0x5c, 0x1e, 0x64, 0x46, 0xce, 0x42, 0x71,
	0x6e, 0x51, 0x18, 0x44, 0xe4, 0x39, 0xd8, 0x81, 0x94, 0x41, 0x78, 0xa6, 0xd4, 0x09, 0xa7, 0xd5,
	0x6d, 0xf6, 0xec, 0xfe, 0x3d, 0x6f, 0xe2, 0xaf, 0x1a, 0xdd, 0x7b, 0x83, 0x51, 0x12, 0x1c, 0x4e,
	0x60, 0xfe, 0xf4, 0x16, 0x72, 0x00, 0x10, 0x66, 0x18, 0x48, 0x8c, 0x4e, 0x02, 0xe9, 0x2c, 0x76,
	0xad, 0x9e, 0xdd, 0xef, 0x78, 0x85, 0xa3, 0x5e, 0xe9, 0xa8, 0x77, 0x5c, 0x5a, 0xee, 0xb7, 0x0d,
	0xfa, 0x50, 0x92, 0x07, 0x30, 0xa7, 0x66, 0x77, 0xda, 0x7a, 0xd3, 0x6a, 0xc9, 0xaa, 0x7d, 0x7d,
	0x2f, 0x30, 0xf3, 0x75, 0x9b, 0xec, 0x41, 0x2b, 0x43, 0x3e, 0x4a, 0x50, 0x38, 0xa0, 0xf5, 0xad,
	0x7b, 0xd5, 0xfc, 0x3d, 0x63, 0xbd, 0x5f, 0xe2, 0x94, 0x5d, 0xa3, 0x64, 0x88, 0xe2, 0x24, 0x64,
	0x79, 0x2a, 0x1d, 0xbb, 0x6b, 0xf5, 0xe6, 0x7d, 0xd0, 0xa5, 0x23, 0x55, 0x21, 0x3b, 0xb0, 0x6c,
	0xb0, 0x06, 0xb2, 0xa4, 0x21, 0x4b, 0xa6, 0xa8, 0x41, 0xee, 0x0f, 0x0b, 0xd6, 0x8e, 0xb4, 0xda,
	0x92, 0x00, 0x3f, 0xe5, 0x28, 0x64, 0x35, 0x2a, 0xab, 0x3e, 0xaa, 0x46, 0x5d, 0x54, 0xcd, 0x9a,
	0xa8, 0xe6, 0xea, 0xa3, 0x9a, 0xff, 0xeb, 0xa8, 0xdc, 0x6f, 0x16, 0x90, 0xd7, 0x28, 0xcd, 0x30,
	0xe2, 0xdf, 0x4c, 0x73, 0x00, 0xc0, 0x83, 0x38, 0x49, 0xf5, 0x95, 0xd3, 0x03, 0xd9, 0xfd, 0x8d,
	0x2b, 0xaa, 0xde, 0x4e, 0x00, 0xfe, 0x14, 0x58, 0xe9, 0xf9, 0xbf, 0xa2, 0x47, 0x70, 0x96, 0x0a,
	0x24, 0xfb, 0xb0, 0x68, 0xee, 0x8b, 0x70, 0xac, 0xfa, 0xc4, 0x27, 0x40, 0x72, 0x58, 0xd1, 0xd1,
	0xd0, 0x3a, 0xb6, 0x6f, 0xd6, 0x61, 0xb8, 0x2a, 0x7a, 0x1e, 0xc3, 0xda, 0x4b, 0x1c, 0xe1, 0x4c,
	0xdc, 0xf5, 0x37, 0xba, 0xff, 0xb3, 0x01, 0x2b, 0x66, 0xc7, 0x3b, 0xcc, 0xce, 0x93, 0x10, 0x49,
	0x0c, 0xcb, 0x95, 0x0f, 0x87, 0xdc, 0x9f, 0x19, 0xe0, 0x9a, 0xef, 0xaa, 0x73, 0xd3, 0x98, 0xee,
	0xfa, 0xd7, 0xcb, 0x5f, 0xdf, 0x1b, 0xab, 0x4f, 0xad, 0x5d, 0x77, 0x89, 0x9e, 0xef, 0xd1, 0xc9,
	0xd4, 0x23, 0xb0, 0xa7, 0x1c, 0x24, 0xee, 0xd5, 0x03, 0x66, 0xe3, 0xee, 0xec, 0xd4, 0x62, 0x0a,
	0x5b, 0xdc, 0x35, 0x4d, 0xb8, 0x42, 0xaa, 0x6c, 0x1c, 0x96, 0x2b, 0x06, 0xcd, 0x8e, 0x75, 0x9d,
	0x7f, 0x9d, 0xdb, 0x33, 0xcf, 0xc1, 0x2b, 0xf5, 0xc0, 0xba, 0xdb, 0x9a, 0x64, 0x73, 0x77, 0x63,
	0x9a, 0x84, 0x7e, 0xfe, 0xe3, 0xf5, 0x97, 0x17, 0x4f, 0x3e, 0x3c, 0x8a, 0x13, 0x79, 0x96, 0x9f,
	0xaa, 0x08, 0xe9, 0x90, 0xa5, 0xf1, 0x10, 0x53, 0x1a, 0xb3, 0x87, 0x8a, 0x95, 0xf2, 0x61, 0x5c,
	0x3c, 0xda, 0xd4, 0xf0, 0x3f, 0x33, 0xff, 0xa7, 0x0b, 0xba, 0xbc, 0xff, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0x3d, 0x59, 0x1b, 0x41, 0x06, 0x00, 0x00,
}
