// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: content/activity.proto

package contentconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	content "github.com/kongken/go-home/pkg/proto/content"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ActivityServiceName is the fully-qualified name of the ActivityService service.
	ActivityServiceName = "uchome.content.ActivityService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ActivityServiceCreateActivityProcedure is the fully-qualified name of the ActivityService's
	// CreateActivity RPC.
	ActivityServiceCreateActivityProcedure = "/uchome.content.ActivityService/CreateActivity"
	// ActivityServiceGetActivityProcedure is the fully-qualified name of the ActivityService's
	// GetActivity RPC.
	ActivityServiceGetActivityProcedure = "/uchome.content.ActivityService/GetActivity"
	// ActivityServiceUpdateActivityProcedure is the fully-qualified name of the ActivityService's
	// UpdateActivity RPC.
	ActivityServiceUpdateActivityProcedure = "/uchome.content.ActivityService/UpdateActivity"
	// ActivityServiceDeleteActivityProcedure is the fully-qualified name of the ActivityService's
	// DeleteActivity RPC.
	ActivityServiceDeleteActivityProcedure = "/uchome.content.ActivityService/DeleteActivity"
	// ActivityServiceGetActivitiesProcedure is the fully-qualified name of the ActivityService's
	// GetActivities RPC.
	ActivityServiceGetActivitiesProcedure = "/uchome.content.ActivityService/GetActivities"
	// ActivityServiceJoinActivityProcedure is the fully-qualified name of the ActivityService's
	// JoinActivity RPC.
	ActivityServiceJoinActivityProcedure = "/uchome.content.ActivityService/JoinActivity"
	// ActivityServiceLeaveActivityProcedure is the fully-qualified name of the ActivityService's
	// LeaveActivity RPC.
	ActivityServiceLeaveActivityProcedure = "/uchome.content.ActivityService/LeaveActivity"
	// ActivityServiceGetParticipantsProcedure is the fully-qualified name of the ActivityService's
	// GetParticipants RPC.
	ActivityServiceGetParticipantsProcedure = "/uchome.content.ActivityService/GetParticipants"
)

// ActivityServiceClient is a client for the uchome.content.ActivityService service.
type ActivityServiceClient interface {
	CreateActivity(context.Context, *connect.Request[content.CreateActivityRequest]) (*connect.Response[content.Activity], error)
	GetActivity(context.Context, *connect.Request[content.GetActivityRequest]) (*connect.Response[content.Activity], error)
	UpdateActivity(context.Context, *connect.Request[content.UpdateActivityRequest]) (*connect.Response[content.Activity], error)
	DeleteActivity(context.Context, *connect.Request[content.DeleteActivityRequest]) (*connect.Response[emptypb.Empty], error)
	GetActivities(context.Context, *connect.Request[content.GetActivitiesRequest]) (*connect.Response[content.GetActivitiesResponse], error)
	JoinActivity(context.Context, *connect.Request[content.JoinActivityRequest]) (*connect.Response[content.ActivityParticipant], error)
	LeaveActivity(context.Context, *connect.Request[content.LeaveActivityRequest]) (*connect.Response[emptypb.Empty], error)
	GetParticipants(context.Context, *connect.Request[content.GetParticipantsRequest]) (*connect.Response[content.GetParticipantsResponse], error)
}

// NewActivityServiceClient constructs a client for the uchome.content.ActivityService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewActivityServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ActivityServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	activityServiceMethods := content.File_content_activity_proto.Services().ByName("ActivityService").Methods()
	return &activityServiceClient{
		createActivity: connect.NewClient[content.CreateActivityRequest, content.Activity](
			httpClient,
			baseURL+ActivityServiceCreateActivityProcedure,
			connect.WithSchema(activityServiceMethods.ByName("CreateActivity")),
			connect.WithClientOptions(opts...),
		),
		getActivity: connect.NewClient[content.GetActivityRequest, content.Activity](
			httpClient,
			baseURL+ActivityServiceGetActivityProcedure,
			connect.WithSchema(activityServiceMethods.ByName("GetActivity")),
			connect.WithClientOptions(opts...),
		),
		updateActivity: connect.NewClient[content.UpdateActivityRequest, content.Activity](
			httpClient,
			baseURL+ActivityServiceUpdateActivityProcedure,
			connect.WithSchema(activityServiceMethods.ByName("UpdateActivity")),
			connect.WithClientOptions(opts...),
		),
		deleteActivity: connect.NewClient[content.DeleteActivityRequest, emptypb.Empty](
			httpClient,
			baseURL+ActivityServiceDeleteActivityProcedure,
			connect.WithSchema(activityServiceMethods.ByName("DeleteActivity")),
			connect.WithClientOptions(opts...),
		),
		getActivities: connect.NewClient[content.GetActivitiesRequest, content.GetActivitiesResponse](
			httpClient,
			baseURL+ActivityServiceGetActivitiesProcedure,
			connect.WithSchema(activityServiceMethods.ByName("GetActivities")),
			connect.WithClientOptions(opts...),
		),
		joinActivity: connect.NewClient[content.JoinActivityRequest, content.ActivityParticipant](
			httpClient,
			baseURL+ActivityServiceJoinActivityProcedure,
			connect.WithSchema(activityServiceMethods.ByName("JoinActivity")),
			connect.WithClientOptions(opts...),
		),
		leaveActivity: connect.NewClient[content.LeaveActivityRequest, emptypb.Empty](
			httpClient,
			baseURL+ActivityServiceLeaveActivityProcedure,
			connect.WithSchema(activityServiceMethods.ByName("LeaveActivity")),
			connect.WithClientOptions(opts...),
		),
		getParticipants: connect.NewClient[content.GetParticipantsRequest, content.GetParticipantsResponse](
			httpClient,
			baseURL+ActivityServiceGetParticipantsProcedure,
			connect.WithSchema(activityServiceMethods.ByName("GetParticipants")),
			connect.WithClientOptions(opts...),
		),
	}
}

// activityServiceClient implements ActivityServiceClient.
type activityServiceClient struct {
	createActivity  *connect.Client[content.CreateActivityRequest, content.Activity]
	getActivity     *connect.Client[content.GetActivityRequest, content.Activity]
	updateActivity  *connect.Client[content.UpdateActivityRequest, content.Activity]
	deleteActivity  *connect.Client[content.DeleteActivityRequest, emptypb.Empty]
	getActivities   *connect.Client[content.GetActivitiesRequest, content.GetActivitiesResponse]
	joinActivity    *connect.Client[content.JoinActivityRequest, content.ActivityParticipant]
	leaveActivity   *connect.Client[content.LeaveActivityRequest, emptypb.Empty]
	getParticipants *connect.Client[content.GetParticipantsRequest, content.GetParticipantsResponse]
}

// CreateActivity calls uchome.content.ActivityService.CreateActivity.
func (c *activityServiceClient) CreateActivity(ctx context.Context, req *connect.Request[content.CreateActivityRequest]) (*connect.Response[content.Activity], error) {
	return c.createActivity.CallUnary(ctx, req)
}

// GetActivity calls uchome.content.ActivityService.GetActivity.
func (c *activityServiceClient) GetActivity(ctx context.Context, req *connect.Request[content.GetActivityRequest]) (*connect.Response[content.Activity], error) {
	return c.getActivity.CallUnary(ctx, req)
}

// UpdateActivity calls uchome.content.ActivityService.UpdateActivity.
func (c *activityServiceClient) UpdateActivity(ctx context.Context, req *connect.Request[content.UpdateActivityRequest]) (*connect.Response[content.Activity], error) {
	return c.updateActivity.CallUnary(ctx, req)
}

// DeleteActivity calls uchome.content.ActivityService.DeleteActivity.
func (c *activityServiceClient) DeleteActivity(ctx context.Context, req *connect.Request[content.DeleteActivityRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteActivity.CallUnary(ctx, req)
}

// GetActivities calls uchome.content.ActivityService.GetActivities.
func (c *activityServiceClient) GetActivities(ctx context.Context, req *connect.Request[content.GetActivitiesRequest]) (*connect.Response[content.GetActivitiesResponse], error) {
	return c.getActivities.CallUnary(ctx, req)
}

// JoinActivity calls uchome.content.ActivityService.JoinActivity.
func (c *activityServiceClient) JoinActivity(ctx context.Context, req *connect.Request[content.JoinActivityRequest]) (*connect.Response[content.ActivityParticipant], error) {
	return c.joinActivity.CallUnary(ctx, req)
}

// LeaveActivity calls uchome.content.ActivityService.LeaveActivity.
func (c *activityServiceClient) LeaveActivity(ctx context.Context, req *connect.Request[content.LeaveActivityRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.leaveActivity.CallUnary(ctx, req)
}

// GetParticipants calls uchome.content.ActivityService.GetParticipants.
func (c *activityServiceClient) GetParticipants(ctx context.Context, req *connect.Request[content.GetParticipantsRequest]) (*connect.Response[content.GetParticipantsResponse], error) {
	return c.getParticipants.CallUnary(ctx, req)
}

// ActivityServiceHandler is an implementation of the uchome.content.ActivityService service.
type ActivityServiceHandler interface {
	CreateActivity(context.Context, *connect.Request[content.CreateActivityRequest]) (*connect.Response[content.Activity], error)
	GetActivity(context.Context, *connect.Request[content.GetActivityRequest]) (*connect.Response[content.Activity], error)
	UpdateActivity(context.Context, *connect.Request[content.UpdateActivityRequest]) (*connect.Response[content.Activity], error)
	DeleteActivity(context.Context, *connect.Request[content.DeleteActivityRequest]) (*connect.Response[emptypb.Empty], error)
	GetActivities(context.Context, *connect.Request[content.GetActivitiesRequest]) (*connect.Response[content.GetActivitiesResponse], error)
	JoinActivity(context.Context, *connect.Request[content.JoinActivityRequest]) (*connect.Response[content.ActivityParticipant], error)
	LeaveActivity(context.Context, *connect.Request[content.LeaveActivityRequest]) (*connect.Response[emptypb.Empty], error)
	GetParticipants(context.Context, *connect.Request[content.GetParticipantsRequest]) (*connect.Response[content.GetParticipantsResponse], error)
}

// NewActivityServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewActivityServiceHandler(svc ActivityServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	activityServiceMethods := content.File_content_activity_proto.Services().ByName("ActivityService").Methods()
	activityServiceCreateActivityHandler := connect.NewUnaryHandler(
		ActivityServiceCreateActivityProcedure,
		svc.CreateActivity,
		connect.WithSchema(activityServiceMethods.ByName("CreateActivity")),
		connect.WithHandlerOptions(opts...),
	)
	activityServiceGetActivityHandler := connect.NewUnaryHandler(
		ActivityServiceGetActivityProcedure,
		svc.GetActivity,
		connect.WithSchema(activityServiceMethods.ByName("GetActivity")),
		connect.WithHandlerOptions(opts...),
	)
	activityServiceUpdateActivityHandler := connect.NewUnaryHandler(
		ActivityServiceUpdateActivityProcedure,
		svc.UpdateActivity,
		connect.WithSchema(activityServiceMethods.ByName("UpdateActivity")),
		connect.WithHandlerOptions(opts...),
	)
	activityServiceDeleteActivityHandler := connect.NewUnaryHandler(
		ActivityServiceDeleteActivityProcedure,
		svc.DeleteActivity,
		connect.WithSchema(activityServiceMethods.ByName("DeleteActivity")),
		connect.WithHandlerOptions(opts...),
	)
	activityServiceGetActivitiesHandler := connect.NewUnaryHandler(
		ActivityServiceGetActivitiesProcedure,
		svc.GetActivities,
		connect.WithSchema(activityServiceMethods.ByName("GetActivities")),
		connect.WithHandlerOptions(opts...),
	)
	activityServiceJoinActivityHandler := connect.NewUnaryHandler(
		ActivityServiceJoinActivityProcedure,
		svc.JoinActivity,
		connect.WithSchema(activityServiceMethods.ByName("JoinActivity")),
		connect.WithHandlerOptions(opts...),
	)
	activityServiceLeaveActivityHandler := connect.NewUnaryHandler(
		ActivityServiceLeaveActivityProcedure,
		svc.LeaveActivity,
		connect.WithSchema(activityServiceMethods.ByName("LeaveActivity")),
		connect.WithHandlerOptions(opts...),
	)
	activityServiceGetParticipantsHandler := connect.NewUnaryHandler(
		ActivityServiceGetParticipantsProcedure,
		svc.GetParticipants,
		connect.WithSchema(activityServiceMethods.ByName("GetParticipants")),
		connect.WithHandlerOptions(opts...),
	)
	return "/uchome.content.ActivityService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ActivityServiceCreateActivityProcedure:
			activityServiceCreateActivityHandler.ServeHTTP(w, r)
		case ActivityServiceGetActivityProcedure:
			activityServiceGetActivityHandler.ServeHTTP(w, r)
		case ActivityServiceUpdateActivityProcedure:
			activityServiceUpdateActivityHandler.ServeHTTP(w, r)
		case ActivityServiceDeleteActivityProcedure:
			activityServiceDeleteActivityHandler.ServeHTTP(w, r)
		case ActivityServiceGetActivitiesProcedure:
			activityServiceGetActivitiesHandler.ServeHTTP(w, r)
		case ActivityServiceJoinActivityProcedure:
			activityServiceJoinActivityHandler.ServeHTTP(w, r)
		case ActivityServiceLeaveActivityProcedure:
			activityServiceLeaveActivityHandler.ServeHTTP(w, r)
		case ActivityServiceGetParticipantsProcedure:
			activityServiceGetParticipantsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedActivityServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedActivityServiceHandler struct{}

func (UnimplementedActivityServiceHandler) CreateActivity(context.Context, *connect.Request[content.CreateActivityRequest]) (*connect.Response[content.Activity], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.CreateActivity is not implemented"))
}

func (UnimplementedActivityServiceHandler) GetActivity(context.Context, *connect.Request[content.GetActivityRequest]) (*connect.Response[content.Activity], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.GetActivity is not implemented"))
}

func (UnimplementedActivityServiceHandler) UpdateActivity(context.Context, *connect.Request[content.UpdateActivityRequest]) (*connect.Response[content.Activity], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.UpdateActivity is not implemented"))
}

func (UnimplementedActivityServiceHandler) DeleteActivity(context.Context, *connect.Request[content.DeleteActivityRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.DeleteActivity is not implemented"))
}

func (UnimplementedActivityServiceHandler) GetActivities(context.Context, *connect.Request[content.GetActivitiesRequest]) (*connect.Response[content.GetActivitiesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.GetActivities is not implemented"))
}

func (UnimplementedActivityServiceHandler) JoinActivity(context.Context, *connect.Request[content.JoinActivityRequest]) (*connect.Response[content.ActivityParticipant], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.JoinActivity is not implemented"))
}

func (UnimplementedActivityServiceHandler) LeaveActivity(context.Context, *connect.Request[content.LeaveActivityRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.LeaveActivity is not implemented"))
}

func (UnimplementedActivityServiceHandler) GetParticipants(context.Context, *connect.Request[content.GetParticipantsRequest]) (*connect.Response[content.GetParticipantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.ActivityService.GetParticipants is not implemented"))
}
