// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: content/album.proto

package contentconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	content "github.com/kongken/go-home/pkg/proto/content"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AlbumServiceName is the fully-qualified name of the AlbumService service.
	AlbumServiceName = "uchome.content.AlbumService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AlbumServiceCreateAlbumProcedure is the fully-qualified name of the AlbumService's CreateAlbum
	// RPC.
	AlbumServiceCreateAlbumProcedure = "/uchome.content.AlbumService/CreateAlbum"
	// AlbumServiceGetAlbumProcedure is the fully-qualified name of the AlbumService's GetAlbum RPC.
	AlbumServiceGetAlbumProcedure = "/uchome.content.AlbumService/GetAlbum"
	// AlbumServiceUpdateAlbumProcedure is the fully-qualified name of the AlbumService's UpdateAlbum
	// RPC.
	AlbumServiceUpdateAlbumProcedure = "/uchome.content.AlbumService/UpdateAlbum"
	// AlbumServiceDeleteAlbumProcedure is the fully-qualified name of the AlbumService's DeleteAlbum
	// RPC.
	AlbumServiceDeleteAlbumProcedure = "/uchome.content.AlbumService/DeleteAlbum"
	// AlbumServiceGetAlbumsProcedure is the fully-qualified name of the AlbumService's GetAlbums RPC.
	AlbumServiceGetAlbumsProcedure = "/uchome.content.AlbumService/GetAlbums"
	// AlbumServiceUploadPhotoProcedure is the fully-qualified name of the AlbumService's UploadPhoto
	// RPC.
	AlbumServiceUploadPhotoProcedure = "/uchome.content.AlbumService/UploadPhoto"
	// AlbumServiceGetPhotosProcedure is the fully-qualified name of the AlbumService's GetPhotos RPC.
	AlbumServiceGetPhotosProcedure = "/uchome.content.AlbumService/GetPhotos"
	// AlbumServiceDeletePhotoProcedure is the fully-qualified name of the AlbumService's DeletePhoto
	// RPC.
	AlbumServiceDeletePhotoProcedure = "/uchome.content.AlbumService/DeletePhoto"
)

// AlbumServiceClient is a client for the uchome.content.AlbumService service.
type AlbumServiceClient interface {
	CreateAlbum(context.Context, *connect.Request[content.CreateAlbumRequest]) (*connect.Response[content.Album], error)
	GetAlbum(context.Context, *connect.Request[content.GetAlbumRequest]) (*connect.Response[content.Album], error)
	UpdateAlbum(context.Context, *connect.Request[content.UpdateAlbumRequest]) (*connect.Response[content.Album], error)
	DeleteAlbum(context.Context, *connect.Request[content.DeleteAlbumRequest]) (*connect.Response[emptypb.Empty], error)
	GetAlbums(context.Context, *connect.Request[content.GetAlbumsRequest]) (*connect.Response[content.GetAlbumsResponse], error)
	UploadPhoto(context.Context, *connect.Request[content.UploadPhotoRequest]) (*connect.Response[content.Photo], error)
	GetPhotos(context.Context, *connect.Request[content.GetPhotosRequest]) (*connect.Response[content.GetPhotosResponse], error)
	DeletePhoto(context.Context, *connect.Request[content.DeletePhotoRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewAlbumServiceClient constructs a client for the uchome.content.AlbumService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAlbumServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AlbumServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	albumServiceMethods := content.File_content_album_proto.Services().ByName("AlbumService").Methods()
	return &albumServiceClient{
		createAlbum: connect.NewClient[content.CreateAlbumRequest, content.Album](
			httpClient,
			baseURL+AlbumServiceCreateAlbumProcedure,
			connect.WithSchema(albumServiceMethods.ByName("CreateAlbum")),
			connect.WithClientOptions(opts...),
		),
		getAlbum: connect.NewClient[content.GetAlbumRequest, content.Album](
			httpClient,
			baseURL+AlbumServiceGetAlbumProcedure,
			connect.WithSchema(albumServiceMethods.ByName("GetAlbum")),
			connect.WithClientOptions(opts...),
		),
		updateAlbum: connect.NewClient[content.UpdateAlbumRequest, content.Album](
			httpClient,
			baseURL+AlbumServiceUpdateAlbumProcedure,
			connect.WithSchema(albumServiceMethods.ByName("UpdateAlbum")),
			connect.WithClientOptions(opts...),
		),
		deleteAlbum: connect.NewClient[content.DeleteAlbumRequest, emptypb.Empty](
			httpClient,
			baseURL+AlbumServiceDeleteAlbumProcedure,
			connect.WithSchema(albumServiceMethods.ByName("DeleteAlbum")),
			connect.WithClientOptions(opts...),
		),
		getAlbums: connect.NewClient[content.GetAlbumsRequest, content.GetAlbumsResponse](
			httpClient,
			baseURL+AlbumServiceGetAlbumsProcedure,
			connect.WithSchema(albumServiceMethods.ByName("GetAlbums")),
			connect.WithClientOptions(opts...),
		),
		uploadPhoto: connect.NewClient[content.UploadPhotoRequest, content.Photo](
			httpClient,
			baseURL+AlbumServiceUploadPhotoProcedure,
			connect.WithSchema(albumServiceMethods.ByName("UploadPhoto")),
			connect.WithClientOptions(opts...),
		),
		getPhotos: connect.NewClient[content.GetPhotosRequest, content.GetPhotosResponse](
			httpClient,
			baseURL+AlbumServiceGetPhotosProcedure,
			connect.WithSchema(albumServiceMethods.ByName("GetPhotos")),
			connect.WithClientOptions(opts...),
		),
		deletePhoto: connect.NewClient[content.DeletePhotoRequest, emptypb.Empty](
			httpClient,
			baseURL+AlbumServiceDeletePhotoProcedure,
			connect.WithSchema(albumServiceMethods.ByName("DeletePhoto")),
			connect.WithClientOptions(opts...),
		),
	}
}

// albumServiceClient implements AlbumServiceClient.
type albumServiceClient struct {
	createAlbum *connect.Client[content.CreateAlbumRequest, content.Album]
	getAlbum    *connect.Client[content.GetAlbumRequest, content.Album]
	updateAlbum *connect.Client[content.UpdateAlbumRequest, content.Album]
	deleteAlbum *connect.Client[content.DeleteAlbumRequest, emptypb.Empty]
	getAlbums   *connect.Client[content.GetAlbumsRequest, content.GetAlbumsResponse]
	uploadPhoto *connect.Client[content.UploadPhotoRequest, content.Photo]
	getPhotos   *connect.Client[content.GetPhotosRequest, content.GetPhotosResponse]
	deletePhoto *connect.Client[content.DeletePhotoRequest, emptypb.Empty]
}

// CreateAlbum calls uchome.content.AlbumService.CreateAlbum.
func (c *albumServiceClient) CreateAlbum(ctx context.Context, req *connect.Request[content.CreateAlbumRequest]) (*connect.Response[content.Album], error) {
	return c.createAlbum.CallUnary(ctx, req)
}

// GetAlbum calls uchome.content.AlbumService.GetAlbum.
func (c *albumServiceClient) GetAlbum(ctx context.Context, req *connect.Request[content.GetAlbumRequest]) (*connect.Response[content.Album], error) {
	return c.getAlbum.CallUnary(ctx, req)
}

// UpdateAlbum calls uchome.content.AlbumService.UpdateAlbum.
func (c *albumServiceClient) UpdateAlbum(ctx context.Context, req *connect.Request[content.UpdateAlbumRequest]) (*connect.Response[content.Album], error) {
	return c.updateAlbum.CallUnary(ctx, req)
}

// DeleteAlbum calls uchome.content.AlbumService.DeleteAlbum.
func (c *albumServiceClient) DeleteAlbum(ctx context.Context, req *connect.Request[content.DeleteAlbumRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deleteAlbum.CallUnary(ctx, req)
}

// GetAlbums calls uchome.content.AlbumService.GetAlbums.
func (c *albumServiceClient) GetAlbums(ctx context.Context, req *connect.Request[content.GetAlbumsRequest]) (*connect.Response[content.GetAlbumsResponse], error) {
	return c.getAlbums.CallUnary(ctx, req)
}

// UploadPhoto calls uchome.content.AlbumService.UploadPhoto.
func (c *albumServiceClient) UploadPhoto(ctx context.Context, req *connect.Request[content.UploadPhotoRequest]) (*connect.Response[content.Photo], error) {
	return c.uploadPhoto.CallUnary(ctx, req)
}

// GetPhotos calls uchome.content.AlbumService.GetPhotos.
func (c *albumServiceClient) GetPhotos(ctx context.Context, req *connect.Request[content.GetPhotosRequest]) (*connect.Response[content.GetPhotosResponse], error) {
	return c.getPhotos.CallUnary(ctx, req)
}

// DeletePhoto calls uchome.content.AlbumService.DeletePhoto.
func (c *albumServiceClient) DeletePhoto(ctx context.Context, req *connect.Request[content.DeletePhotoRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.deletePhoto.CallUnary(ctx, req)
}

// AlbumServiceHandler is an implementation of the uchome.content.AlbumService service.
type AlbumServiceHandler interface {
	CreateAlbum(context.Context, *connect.Request[content.CreateAlbumRequest]) (*connect.Response[content.Album], error)
	GetAlbum(context.Context, *connect.Request[content.GetAlbumRequest]) (*connect.Response[content.Album], error)
	UpdateAlbum(context.Context, *connect.Request[content.UpdateAlbumRequest]) (*connect.Response[content.Album], error)
	DeleteAlbum(context.Context, *connect.Request[content.DeleteAlbumRequest]) (*connect.Response[emptypb.Empty], error)
	GetAlbums(context.Context, *connect.Request[content.GetAlbumsRequest]) (*connect.Response[content.GetAlbumsResponse], error)
	UploadPhoto(context.Context, *connect.Request[content.UploadPhotoRequest]) (*connect.Response[content.Photo], error)
	GetPhotos(context.Context, *connect.Request[content.GetPhotosRequest]) (*connect.Response[content.GetPhotosResponse], error)
	DeletePhoto(context.Context, *connect.Request[content.DeletePhotoRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewAlbumServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAlbumServiceHandler(svc AlbumServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	albumServiceMethods := content.File_content_album_proto.Services().ByName("AlbumService").Methods()
	albumServiceCreateAlbumHandler := connect.NewUnaryHandler(
		AlbumServiceCreateAlbumProcedure,
		svc.CreateAlbum,
		connect.WithSchema(albumServiceMethods.ByName("CreateAlbum")),
		connect.WithHandlerOptions(opts...),
	)
	albumServiceGetAlbumHandler := connect.NewUnaryHandler(
		AlbumServiceGetAlbumProcedure,
		svc.GetAlbum,
		connect.WithSchema(albumServiceMethods.ByName("GetAlbum")),
		connect.WithHandlerOptions(opts...),
	)
	albumServiceUpdateAlbumHandler := connect.NewUnaryHandler(
		AlbumServiceUpdateAlbumProcedure,
		svc.UpdateAlbum,
		connect.WithSchema(albumServiceMethods.ByName("UpdateAlbum")),
		connect.WithHandlerOptions(opts...),
	)
	albumServiceDeleteAlbumHandler := connect.NewUnaryHandler(
		AlbumServiceDeleteAlbumProcedure,
		svc.DeleteAlbum,
		connect.WithSchema(albumServiceMethods.ByName("DeleteAlbum")),
		connect.WithHandlerOptions(opts...),
	)
	albumServiceGetAlbumsHandler := connect.NewUnaryHandler(
		AlbumServiceGetAlbumsProcedure,
		svc.GetAlbums,
		connect.WithSchema(albumServiceMethods.ByName("GetAlbums")),
		connect.WithHandlerOptions(opts...),
	)
	albumServiceUploadPhotoHandler := connect.NewUnaryHandler(
		AlbumServiceUploadPhotoProcedure,
		svc.UploadPhoto,
		connect.WithSchema(albumServiceMethods.ByName("UploadPhoto")),
		connect.WithHandlerOptions(opts...),
	)
	albumServiceGetPhotosHandler := connect.NewUnaryHandler(
		AlbumServiceGetPhotosProcedure,
		svc.GetPhotos,
		connect.WithSchema(albumServiceMethods.ByName("GetPhotos")),
		connect.WithHandlerOptions(opts...),
	)
	albumServiceDeletePhotoHandler := connect.NewUnaryHandler(
		AlbumServiceDeletePhotoProcedure,
		svc.DeletePhoto,
		connect.WithSchema(albumServiceMethods.ByName("DeletePhoto")),
		connect.WithHandlerOptions(opts...),
	)
	return "/uchome.content.AlbumService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AlbumServiceCreateAlbumProcedure:
			albumServiceCreateAlbumHandler.ServeHTTP(w, r)
		case AlbumServiceGetAlbumProcedure:
			albumServiceGetAlbumHandler.ServeHTTP(w, r)
		case AlbumServiceUpdateAlbumProcedure:
			albumServiceUpdateAlbumHandler.ServeHTTP(w, r)
		case AlbumServiceDeleteAlbumProcedure:
			albumServiceDeleteAlbumHandler.ServeHTTP(w, r)
		case AlbumServiceGetAlbumsProcedure:
			albumServiceGetAlbumsHandler.ServeHTTP(w, r)
		case AlbumServiceUploadPhotoProcedure:
			albumServiceUploadPhotoHandler.ServeHTTP(w, r)
		case AlbumServiceGetPhotosProcedure:
			albumServiceGetPhotosHandler.ServeHTTP(w, r)
		case AlbumServiceDeletePhotoProcedure:
			albumServiceDeletePhotoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAlbumServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAlbumServiceHandler struct{}

func (UnimplementedAlbumServiceHandler) CreateAlbum(context.Context, *connect.Request[content.CreateAlbumRequest]) (*connect.Response[content.Album], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.CreateAlbum is not implemented"))
}

func (UnimplementedAlbumServiceHandler) GetAlbum(context.Context, *connect.Request[content.GetAlbumRequest]) (*connect.Response[content.Album], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.GetAlbum is not implemented"))
}

func (UnimplementedAlbumServiceHandler) UpdateAlbum(context.Context, *connect.Request[content.UpdateAlbumRequest]) (*connect.Response[content.Album], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.UpdateAlbum is not implemented"))
}

func (UnimplementedAlbumServiceHandler) DeleteAlbum(context.Context, *connect.Request[content.DeleteAlbumRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.DeleteAlbum is not implemented"))
}

func (UnimplementedAlbumServiceHandler) GetAlbums(context.Context, *connect.Request[content.GetAlbumsRequest]) (*connect.Response[content.GetAlbumsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.GetAlbums is not implemented"))
}

func (UnimplementedAlbumServiceHandler) UploadPhoto(context.Context, *connect.Request[content.UploadPhotoRequest]) (*connect.Response[content.Photo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.UploadPhoto is not implemented"))
}

func (UnimplementedAlbumServiceHandler) GetPhotos(context.Context, *connect.Request[content.GetPhotosRequest]) (*connect.Response[content.GetPhotosResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.GetPhotos is not implemented"))
}

func (UnimplementedAlbumServiceHandler) DeletePhoto(context.Context, *connect.Request[content.DeletePhotoRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.content.AlbumService.DeletePhoto is not implemented"))
}
