// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: group/group.proto

package groupconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	group "github.com/kongken/go-home/pkg/proto/group"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GroupServiceName is the fully-qualified name of the GroupService service.
	GroupServiceName = "uchome.group.GroupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GroupServiceCreateGroupProcedure is the fully-qualified name of the GroupService's CreateGroup
	// RPC.
	GroupServiceCreateGroupProcedure = "/uchome.group.GroupService/CreateGroup"
	// GroupServiceGetGroupProcedure is the fully-qualified name of the GroupService's GetGroup RPC.
	GroupServiceGetGroupProcedure = "/uchome.group.GroupService/GetGroup"
	// GroupServiceGetGroupsProcedure is the fully-qualified name of the GroupService's GetGroups RPC.
	GroupServiceGetGroupsProcedure = "/uchome.group.GroupService/GetGroups"
	// GroupServiceJoinGroupProcedure is the fully-qualified name of the GroupService's JoinGroup RPC.
	GroupServiceJoinGroupProcedure = "/uchome.group.GroupService/JoinGroup"
	// GroupServiceLeaveGroupProcedure is the fully-qualified name of the GroupService's LeaveGroup RPC.
	GroupServiceLeaveGroupProcedure = "/uchome.group.GroupService/LeaveGroup"
	// GroupServiceGetGroupMembersProcedure is the fully-qualified name of the GroupService's
	// GetGroupMembers RPC.
	GroupServiceGetGroupMembersProcedure = "/uchome.group.GroupService/GetGroupMembers"
)

// GroupServiceClient is a client for the uchome.group.GroupService service.
type GroupServiceClient interface {
	// 创建群组
	CreateGroup(context.Context, *connect.Request[group.CreateGroupRequest]) (*connect.Response[group.Group], error)
	// 获取群组详情
	GetGroup(context.Context, *connect.Request[group.GetGroupRequest]) (*connect.Response[group.Group], error)
	// 获取群组列表
	GetGroups(context.Context, *connect.Request[group.GetGroupsRequest]) (*connect.Response[group.GetGroupsResponse], error)
	// 加入群组
	JoinGroup(context.Context, *connect.Request[group.JoinGroupRequest]) (*connect.Response[group.GroupMember], error)
	// 退出群组
	LeaveGroup(context.Context, *connect.Request[group.LeaveGroupRequest]) (*connect.Response[emptypb.Empty], error)
	// 获取群组成员
	GetGroupMembers(context.Context, *connect.Request[group.GetGroupMembersRequest]) (*connect.Response[group.GetGroupMembersResponse], error)
}

// NewGroupServiceClient constructs a client for the uchome.group.GroupService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGroupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GroupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	groupServiceMethods := group.File_group_group_proto.Services().ByName("GroupService").Methods()
	return &groupServiceClient{
		createGroup: connect.NewClient[group.CreateGroupRequest, group.Group](
			httpClient,
			baseURL+GroupServiceCreateGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("CreateGroup")),
			connect.WithClientOptions(opts...),
		),
		getGroup: connect.NewClient[group.GetGroupRequest, group.Group](
			httpClient,
			baseURL+GroupServiceGetGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("GetGroup")),
			connect.WithClientOptions(opts...),
		),
		getGroups: connect.NewClient[group.GetGroupsRequest, group.GetGroupsResponse](
			httpClient,
			baseURL+GroupServiceGetGroupsProcedure,
			connect.WithSchema(groupServiceMethods.ByName("GetGroups")),
			connect.WithClientOptions(opts...),
		),
		joinGroup: connect.NewClient[group.JoinGroupRequest, group.GroupMember](
			httpClient,
			baseURL+GroupServiceJoinGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("JoinGroup")),
			connect.WithClientOptions(opts...),
		),
		leaveGroup: connect.NewClient[group.LeaveGroupRequest, emptypb.Empty](
			httpClient,
			baseURL+GroupServiceLeaveGroupProcedure,
			connect.WithSchema(groupServiceMethods.ByName("LeaveGroup")),
			connect.WithClientOptions(opts...),
		),
		getGroupMembers: connect.NewClient[group.GetGroupMembersRequest, group.GetGroupMembersResponse](
			httpClient,
			baseURL+GroupServiceGetGroupMembersProcedure,
			connect.WithSchema(groupServiceMethods.ByName("GetGroupMembers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// groupServiceClient implements GroupServiceClient.
type groupServiceClient struct {
	createGroup     *connect.Client[group.CreateGroupRequest, group.Group]
	getGroup        *connect.Client[group.GetGroupRequest, group.Group]
	getGroups       *connect.Client[group.GetGroupsRequest, group.GetGroupsResponse]
	joinGroup       *connect.Client[group.JoinGroupRequest, group.GroupMember]
	leaveGroup      *connect.Client[group.LeaveGroupRequest, emptypb.Empty]
	getGroupMembers *connect.Client[group.GetGroupMembersRequest, group.GetGroupMembersResponse]
}

// CreateGroup calls uchome.group.GroupService.CreateGroup.
func (c *groupServiceClient) CreateGroup(ctx context.Context, req *connect.Request[group.CreateGroupRequest]) (*connect.Response[group.Group], error) {
	return c.createGroup.CallUnary(ctx, req)
}

// GetGroup calls uchome.group.GroupService.GetGroup.
func (c *groupServiceClient) GetGroup(ctx context.Context, req *connect.Request[group.GetGroupRequest]) (*connect.Response[group.Group], error) {
	return c.getGroup.CallUnary(ctx, req)
}

// GetGroups calls uchome.group.GroupService.GetGroups.
func (c *groupServiceClient) GetGroups(ctx context.Context, req *connect.Request[group.GetGroupsRequest]) (*connect.Response[group.GetGroupsResponse], error) {
	return c.getGroups.CallUnary(ctx, req)
}

// JoinGroup calls uchome.group.GroupService.JoinGroup.
func (c *groupServiceClient) JoinGroup(ctx context.Context, req *connect.Request[group.JoinGroupRequest]) (*connect.Response[group.GroupMember], error) {
	return c.joinGroup.CallUnary(ctx, req)
}

// LeaveGroup calls uchome.group.GroupService.LeaveGroup.
func (c *groupServiceClient) LeaveGroup(ctx context.Context, req *connect.Request[group.LeaveGroupRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.leaveGroup.CallUnary(ctx, req)
}

// GetGroupMembers calls uchome.group.GroupService.GetGroupMembers.
func (c *groupServiceClient) GetGroupMembers(ctx context.Context, req *connect.Request[group.GetGroupMembersRequest]) (*connect.Response[group.GetGroupMembersResponse], error) {
	return c.getGroupMembers.CallUnary(ctx, req)
}

// GroupServiceHandler is an implementation of the uchome.group.GroupService service.
type GroupServiceHandler interface {
	// 创建群组
	CreateGroup(context.Context, *connect.Request[group.CreateGroupRequest]) (*connect.Response[group.Group], error)
	// 获取群组详情
	GetGroup(context.Context, *connect.Request[group.GetGroupRequest]) (*connect.Response[group.Group], error)
	// 获取群组列表
	GetGroups(context.Context, *connect.Request[group.GetGroupsRequest]) (*connect.Response[group.GetGroupsResponse], error)
	// 加入群组
	JoinGroup(context.Context, *connect.Request[group.JoinGroupRequest]) (*connect.Response[group.GroupMember], error)
	// 退出群组
	LeaveGroup(context.Context, *connect.Request[group.LeaveGroupRequest]) (*connect.Response[emptypb.Empty], error)
	// 获取群组成员
	GetGroupMembers(context.Context, *connect.Request[group.GetGroupMembersRequest]) (*connect.Response[group.GetGroupMembersResponse], error)
}

// NewGroupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGroupServiceHandler(svc GroupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	groupServiceMethods := group.File_group_group_proto.Services().ByName("GroupService").Methods()
	groupServiceCreateGroupHandler := connect.NewUnaryHandler(
		GroupServiceCreateGroupProcedure,
		svc.CreateGroup,
		connect.WithSchema(groupServiceMethods.ByName("CreateGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceGetGroupHandler := connect.NewUnaryHandler(
		GroupServiceGetGroupProcedure,
		svc.GetGroup,
		connect.WithSchema(groupServiceMethods.ByName("GetGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceGetGroupsHandler := connect.NewUnaryHandler(
		GroupServiceGetGroupsProcedure,
		svc.GetGroups,
		connect.WithSchema(groupServiceMethods.ByName("GetGroups")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceJoinGroupHandler := connect.NewUnaryHandler(
		GroupServiceJoinGroupProcedure,
		svc.JoinGroup,
		connect.WithSchema(groupServiceMethods.ByName("JoinGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceLeaveGroupHandler := connect.NewUnaryHandler(
		GroupServiceLeaveGroupProcedure,
		svc.LeaveGroup,
		connect.WithSchema(groupServiceMethods.ByName("LeaveGroup")),
		connect.WithHandlerOptions(opts...),
	)
	groupServiceGetGroupMembersHandler := connect.NewUnaryHandler(
		GroupServiceGetGroupMembersProcedure,
		svc.GetGroupMembers,
		connect.WithSchema(groupServiceMethods.ByName("GetGroupMembers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/uchome.group.GroupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GroupServiceCreateGroupProcedure:
			groupServiceCreateGroupHandler.ServeHTTP(w, r)
		case GroupServiceGetGroupProcedure:
			groupServiceGetGroupHandler.ServeHTTP(w, r)
		case GroupServiceGetGroupsProcedure:
			groupServiceGetGroupsHandler.ServeHTTP(w, r)
		case GroupServiceJoinGroupProcedure:
			groupServiceJoinGroupHandler.ServeHTTP(w, r)
		case GroupServiceLeaveGroupProcedure:
			groupServiceLeaveGroupHandler.ServeHTTP(w, r)
		case GroupServiceGetGroupMembersProcedure:
			groupServiceGetGroupMembersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGroupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGroupServiceHandler struct{}

func (UnimplementedGroupServiceHandler) CreateGroup(context.Context, *connect.Request[group.CreateGroupRequest]) (*connect.Response[group.Group], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.group.GroupService.CreateGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) GetGroup(context.Context, *connect.Request[group.GetGroupRequest]) (*connect.Response[group.Group], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.group.GroupService.GetGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) GetGroups(context.Context, *connect.Request[group.GetGroupsRequest]) (*connect.Response[group.GetGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.group.GroupService.GetGroups is not implemented"))
}

func (UnimplementedGroupServiceHandler) JoinGroup(context.Context, *connect.Request[group.JoinGroupRequest]) (*connect.Response[group.GroupMember], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.group.GroupService.JoinGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) LeaveGroup(context.Context, *connect.Request[group.LeaveGroupRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.group.GroupService.LeaveGroup is not implemented"))
}

func (UnimplementedGroupServiceHandler) GetGroupMembers(context.Context, *connect.Request[group.GetGroupMembersRequest]) (*connect.Response[group.GetGroupMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.group.GroupService.GetGroupMembers is not implemented"))
}
