// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kongken/go-home/internal/cache"
	"github.com/kongken/go-home/internal/handler"
	"github.com/kongken/go-home/internal/repository"
	"github.com/kongken/go-home/internal/service"
	appwire "github.com/kongken/go-home/internal/wire"
)

// InitializeHandlers 使用 Wire 初始化所有 Handler
func InitializeHandlers() (*appwire.Handlers, error) {
	// Repository
	userRepo := repository.NewUserRepositoryButterfly()
	blogRepo := repository.NewBlogRepositoryButterfly()
	feedRepo := repository.NewFeedRepositoryButterfly()
	friendRepo := repository.NewFriendRepositoryButterfly()
	groupRepo := repository.NewGroupRepositoryButterfly()
	messageRepo := repository.NewMessageRepositoryButterfly()
	notifRepo := repository.NewNotificationRepositoryButterfly()
	commentRepo := repository.NewCommentRepositoryButterfly()
	albumRepo := repository.NewAlbumRepositoryButterfly()
	settingsRepo := repository.NewSettingsRepositoryButterfly()

	// Cache
	redisCache := cache.NewRedisCache()

	// Service
	userService := service.NewUserService(userRepo, redisCache)
	blogService := service.NewBlogService(blogRepo, redisCache)
	feedService := service.NewFeedService(feedRepo, redisCache)
	friendService := service.NewFriendService(friendRepo)
	groupService := service.NewGroupService(groupRepo)
	messageService := service.NewMessageService(messageRepo)
	notifService := service.NewNotificationService(notifRepo)
	commentService := service.NewCommentService(commentRepo)
	albumService := service.NewAlbumService(albumRepo)
	settingsService := service.NewSettingsService(settingsRepo)

	// Handler
	userHandler := handler.NewUserHandler(userService)
	blogHandler := handler.NewBlogHandler(blogService)
	feedHandler := handler.NewFeedHandler(feedService)
	friendHandler := handler.NewFriendHandler(friendService)
	groupHandler := handler.NewGroupHandler(groupService)
	messageHandler := handler.NewMessageHandler(messageService)
	notifHandler := handler.NewNotificationHandler(notifService)
	commentHandler := handler.NewCommentHandler(commentService)
	albumHandler := handler.NewAlbumHandler(albumService)
	settingsHandler := handler.NewSettingsHandler(settingsService)

	// Handlers
	handlers := appwire.NewHandlers(
		userHandler,
		blogHandler,
		feedHandler,
		friendHandler,
		groupHandler,
		messageHandler,
		notifHandler,
		commentHandler,
		albumHandler,
		settingsHandler,
	)

	return handlers, nil
}