// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: user/user.proto

package userconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	user "github.com/kongken/go-home/pkg/proto/user"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "uchome.user.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceRegisterProcedure is the fully-qualified name of the UserService's Register RPC.
	UserServiceRegisterProcedure = "/uchome.user.UserService/Register"
	// UserServiceLoginProcedure is the fully-qualified name of the UserService's Login RPC.
	UserServiceLoginProcedure = "/uchome.user.UserService/Login"
	// UserServiceRefreshTokenProcedure is the fully-qualified name of the UserService's RefreshToken
	// RPC.
	UserServiceRefreshTokenProcedure = "/uchome.user.UserService/RefreshToken"
	// UserServiceLogoutProcedure is the fully-qualified name of the UserService's Logout RPC.
	UserServiceLogoutProcedure = "/uchome.user.UserService/Logout"
	// UserServiceChangePasswordProcedure is the fully-qualified name of the UserService's
	// ChangePassword RPC.
	UserServiceChangePasswordProcedure = "/uchome.user.UserService/ChangePassword"
	// UserServiceGetMeProcedure is the fully-qualified name of the UserService's GetMe RPC.
	UserServiceGetMeProcedure = "/uchome.user.UserService/GetMe"
	// UserServiceGetUserProcedure is the fully-qualified name of the UserService's GetUser RPC.
	UserServiceGetUserProcedure = "/uchome.user.UserService/GetUser"
	// UserServiceUpdateUserProcedure is the fully-qualified name of the UserService's UpdateUser RPC.
	UserServiceUpdateUserProcedure = "/uchome.user.UserService/UpdateUser"
	// UserServiceSearchUsersProcedure is the fully-qualified name of the UserService's SearchUsers RPC.
	UserServiceSearchUsersProcedure = "/uchome.user.UserService/SearchUsers"
)

// UserServiceClient is a client for the uchome.user.UserService service.
type UserServiceClient interface {
	// 用户注册
	Register(context.Context, *connect.Request[user.RegisterRequest]) (*connect.Response[user.AuthResponse], error)
	// 用户登录
	Login(context.Context, *connect.Request[user.LoginRequest]) (*connect.Response[user.AuthResponse], error)
	// 刷新Token
	RefreshToken(context.Context, *connect.Request[user.RefreshTokenRequest]) (*connect.Response[user.AuthResponse], error)
	// 登出
	Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	// 修改密码
	ChangePassword(context.Context, *connect.Request[user.ChangePasswordRequest]) (*connect.Response[emptypb.Empty], error)
	// 获取当前用户信息
	GetMe(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[user.User], error)
	// 获取指定用户信息
	GetUser(context.Context, *connect.Request[user.GetUserRequest]) (*connect.Response[user.User], error)
	// 更新用户信息
	UpdateUser(context.Context, *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.User], error)
	// 搜索用户
	SearchUsers(context.Context, *connect.Request[user.SearchUsersRequest]) (*connect.Response[user.SearchUsersResponse], error)
}

// NewUserServiceClient constructs a client for the uchome.user.UserService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUserServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UserServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	userServiceMethods := user.File_user_user_proto.Services().ByName("UserService").Methods()
	return &userServiceClient{
		register: connect.NewClient[user.RegisterRequest, user.AuthResponse](
			httpClient,
			baseURL+UserServiceRegisterProcedure,
			connect.WithSchema(userServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[user.LoginRequest, user.AuthResponse](
			httpClient,
			baseURL+UserServiceLoginProcedure,
			connect.WithSchema(userServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		refreshToken: connect.NewClient[user.RefreshTokenRequest, user.AuthResponse](
			httpClient,
			baseURL+UserServiceRefreshTokenProcedure,
			connect.WithSchema(userServiceMethods.ByName("RefreshToken")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[emptypb.Empty, emptypb.Empty](
			httpClient,
			baseURL+UserServiceLogoutProcedure,
			connect.WithSchema(userServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
		changePassword: connect.NewClient[user.ChangePasswordRequest, emptypb.Empty](
			httpClient,
			baseURL+UserServiceChangePasswordProcedure,
			connect.WithSchema(userServiceMethods.ByName("ChangePassword")),
			connect.WithClientOptions(opts...),
		),
		getMe: connect.NewClient[emptypb.Empty, user.User](
			httpClient,
			baseURL+UserServiceGetMeProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
		getUser: connect.NewClient[user.GetUserRequest, user.User](
			httpClient,
			baseURL+UserServiceGetUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("GetUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[user.UpdateUserRequest, user.User](
			httpClient,
			baseURL+UserServiceUpdateUserProcedure,
			connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		searchUsers: connect.NewClient[user.SearchUsersRequest, user.SearchUsersResponse](
			httpClient,
			baseURL+UserServiceSearchUsersProcedure,
			connect.WithSchema(userServiceMethods.ByName("SearchUsers")),
			connect.WithClientOptions(opts...),
		),
	}
}

// userServiceClient implements UserServiceClient.
type userServiceClient struct {
	register       *connect.Client[user.RegisterRequest, user.AuthResponse]
	login          *connect.Client[user.LoginRequest, user.AuthResponse]
	refreshToken   *connect.Client[user.RefreshTokenRequest, user.AuthResponse]
	logout         *connect.Client[emptypb.Empty, emptypb.Empty]
	changePassword *connect.Client[user.ChangePasswordRequest, emptypb.Empty]
	getMe          *connect.Client[emptypb.Empty, user.User]
	getUser        *connect.Client[user.GetUserRequest, user.User]
	updateUser     *connect.Client[user.UpdateUserRequest, user.User]
	searchUsers    *connect.Client[user.SearchUsersRequest, user.SearchUsersResponse]
}

// Register calls uchome.user.UserService.Register.
func (c *userServiceClient) Register(ctx context.Context, req *connect.Request[user.RegisterRequest]) (*connect.Response[user.AuthResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls uchome.user.UserService.Login.
func (c *userServiceClient) Login(ctx context.Context, req *connect.Request[user.LoginRequest]) (*connect.Response[user.AuthResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// RefreshToken calls uchome.user.UserService.RefreshToken.
func (c *userServiceClient) RefreshToken(ctx context.Context, req *connect.Request[user.RefreshTokenRequest]) (*connect.Response[user.AuthResponse], error) {
	return c.refreshToken.CallUnary(ctx, req)
}

// Logout calls uchome.user.UserService.Logout.
func (c *userServiceClient) Logout(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return c.logout.CallUnary(ctx, req)
}

// ChangePassword calls uchome.user.UserService.ChangePassword.
func (c *userServiceClient) ChangePassword(ctx context.Context, req *connect.Request[user.ChangePasswordRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.changePassword.CallUnary(ctx, req)
}

// GetMe calls uchome.user.UserService.GetMe.
func (c *userServiceClient) GetMe(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[user.User], error) {
	return c.getMe.CallUnary(ctx, req)
}

// GetUser calls uchome.user.UserService.GetUser.
func (c *userServiceClient) GetUser(ctx context.Context, req *connect.Request[user.GetUserRequest]) (*connect.Response[user.User], error) {
	return c.getUser.CallUnary(ctx, req)
}

// UpdateUser calls uchome.user.UserService.UpdateUser.
func (c *userServiceClient) UpdateUser(ctx context.Context, req *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.User], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// SearchUsers calls uchome.user.UserService.SearchUsers.
func (c *userServiceClient) SearchUsers(ctx context.Context, req *connect.Request[user.SearchUsersRequest]) (*connect.Response[user.SearchUsersResponse], error) {
	return c.searchUsers.CallUnary(ctx, req)
}

// UserServiceHandler is an implementation of the uchome.user.UserService service.
type UserServiceHandler interface {
	// 用户注册
	Register(context.Context, *connect.Request[user.RegisterRequest]) (*connect.Response[user.AuthResponse], error)
	// 用户登录
	Login(context.Context, *connect.Request[user.LoginRequest]) (*connect.Response[user.AuthResponse], error)
	// 刷新Token
	RefreshToken(context.Context, *connect.Request[user.RefreshTokenRequest]) (*connect.Response[user.AuthResponse], error)
	// 登出
	Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error)
	// 修改密码
	ChangePassword(context.Context, *connect.Request[user.ChangePasswordRequest]) (*connect.Response[emptypb.Empty], error)
	// 获取当前用户信息
	GetMe(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[user.User], error)
	// 获取指定用户信息
	GetUser(context.Context, *connect.Request[user.GetUserRequest]) (*connect.Response[user.User], error)
	// 更新用户信息
	UpdateUser(context.Context, *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.User], error)
	// 搜索用户
	SearchUsers(context.Context, *connect.Request[user.SearchUsersRequest]) (*connect.Response[user.SearchUsersResponse], error)
}

// NewUserServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUserServiceHandler(svc UserServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	userServiceMethods := user.File_user_user_proto.Services().ByName("UserService").Methods()
	userServiceRegisterHandler := connect.NewUnaryHandler(
		UserServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(userServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceLoginHandler := connect.NewUnaryHandler(
		UserServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(userServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceRefreshTokenHandler := connect.NewUnaryHandler(
		UserServiceRefreshTokenProcedure,
		svc.RefreshToken,
		connect.WithSchema(userServiceMethods.ByName("RefreshToken")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceLogoutHandler := connect.NewUnaryHandler(
		UserServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(userServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceChangePasswordHandler := connect.NewUnaryHandler(
		UserServiceChangePasswordProcedure,
		svc.ChangePassword,
		connect.WithSchema(userServiceMethods.ByName("ChangePassword")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetMeHandler := connect.NewUnaryHandler(
		UserServiceGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(userServiceMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceGetUserHandler := connect.NewUnaryHandler(
		UserServiceGetUserProcedure,
		svc.GetUser,
		connect.WithSchema(userServiceMethods.ByName("GetUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceUpdateUserHandler := connect.NewUnaryHandler(
		UserServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(userServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	userServiceSearchUsersHandler := connect.NewUnaryHandler(
		UserServiceSearchUsersProcedure,
		svc.SearchUsers,
		connect.WithSchema(userServiceMethods.ByName("SearchUsers")),
		connect.WithHandlerOptions(opts...),
	)
	return "/uchome.user.UserService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UserServiceRegisterProcedure:
			userServiceRegisterHandler.ServeHTTP(w, r)
		case UserServiceLoginProcedure:
			userServiceLoginHandler.ServeHTTP(w, r)
		case UserServiceRefreshTokenProcedure:
			userServiceRefreshTokenHandler.ServeHTTP(w, r)
		case UserServiceLogoutProcedure:
			userServiceLogoutHandler.ServeHTTP(w, r)
		case UserServiceChangePasswordProcedure:
			userServiceChangePasswordHandler.ServeHTTP(w, r)
		case UserServiceGetMeProcedure:
			userServiceGetMeHandler.ServeHTTP(w, r)
		case UserServiceGetUserProcedure:
			userServiceGetUserHandler.ServeHTTP(w, r)
		case UserServiceUpdateUserProcedure:
			userServiceUpdateUserHandler.ServeHTTP(w, r)
		case UserServiceSearchUsersProcedure:
			userServiceSearchUsersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUserServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUserServiceHandler struct{}

func (UnimplementedUserServiceHandler) Register(context.Context, *connect.Request[user.RegisterRequest]) (*connect.Response[user.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.Register is not implemented"))
}

func (UnimplementedUserServiceHandler) Login(context.Context, *connect.Request[user.LoginRequest]) (*connect.Response[user.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.Login is not implemented"))
}

func (UnimplementedUserServiceHandler) RefreshToken(context.Context, *connect.Request[user.RefreshTokenRequest]) (*connect.Response[user.AuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.RefreshToken is not implemented"))
}

func (UnimplementedUserServiceHandler) Logout(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.Logout is not implemented"))
}

func (UnimplementedUserServiceHandler) ChangePassword(context.Context, *connect.Request[user.ChangePasswordRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.ChangePassword is not implemented"))
}

func (UnimplementedUserServiceHandler) GetMe(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[user.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.GetMe is not implemented"))
}

func (UnimplementedUserServiceHandler) GetUser(context.Context, *connect.Request[user.GetUserRequest]) (*connect.Response[user.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.GetUser is not implemented"))
}

func (UnimplementedUserServiceHandler) UpdateUser(context.Context, *connect.Request[user.UpdateUserRequest]) (*connect.Response[user.User], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.UpdateUser is not implemented"))
}

func (UnimplementedUserServiceHandler) SearchUsers(context.Context, *connect.Request[user.SearchUsersRequest]) (*connect.Response[user.SearchUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("uchome.user.UserService.SearchUsers is not implemented"))
}
